### ISSUE TITLE
Do not override deinit

### ISSUE THREAD

**Issue by rbeeger** [Brightify/Cuckoo#104]
In a class to be mocked I have a `deinit` like this

```
    deinit {
        // do something
    }
```

and Cuckoo generates 
```
    override func deinit() {
        return manager.call("deinit", parameters: (), original: observed.map { o in return { () in o.deinit() } })
    }
```

That doesn't work. Just ignore `deinit` while generating mocks.

**Comment by TadeasKriz** [comment]
We got a PR from @mrgerych today and I'd like to get it all merged no later than the end of this week. Thanks for reporting this!

**Comment by mrgerych** [comment]
@TadeasKriz you can close this issue
