### ISSUE TITLE
Forced @escaping attribute for closure arguments in protocols

### ISSUE THREAD

**Issue by bhargavg** [Brightify/Cuckoo#114]
If I have a protocol like:

```swift
protocol Foo {
    func bar(x: Int, y: (Int) -> Void)
}
```

The generated mock is failing to compile with error: `Non-escaping parameter 'y' may only be called`. To make it compile, I have to make `y` `@escaping`.

Questions:
1. Is this a known issue?
2. If yes, is there any workaround (without making parameters escaping)?

**Comment by TadeasKriz** [comment]
I'm sorry for the lack of my reply. This should be already fixed.
