### ISSUE TITLE
Generator Build issues: FileKit + Swiftlint 0.17.0

### ISSUE THREAD

**Issue by benjamin-hergert-hs** [Brightify/Cuckoo#117]
The Generator's currently referenced version of **FileKit** ([_d91beae_](https://github.com/nvzqz/FileKit/tree/d91beae40e3ca830e32eb7177f096063b0d25702)) breaks with Swiftlint 0.17.0 installed due to a `shorthand_operator` error.

**FileKit** has since fixed this issue on their [develop](https://github.com/nvzqz/FileKit/commit/3bd3facb1744e1c3fdbb592110d0dca8cd70e55e) branch.

**Comment by TadeasKriz** [comment]
Thanks for the report, it'll be soon fixed with the switch to Swift Package Manager.

**Comment by TadeasKriz** [comment]
This should be fixed in `0.9.0`. If not, please reopen this issue. Thanks!
