### ISSUE TITLE
Can Cuckoo handle stubbing with closures?

### ISSUE THREAD

**Issue by samskiter** [Brightify/Cuckoo#127]
I'm trying to stub a method like but getting a swift compiler every time... The method looks like:

```
typealias MyCompletion = (_ result: MyResult<[MySuccessType], MyErrorType>) -> Void

protocol MyProtocol {

    func doThingWithCompletion(completion: @escaping MyCompletion)
}
```

**Comment by samskiter** [comment]
NVM, missed the argument naming (`completion`) and swift gives a terrible output

**Comment by dushantSW** [comment]
@samskiter How did you solve this? Could you please provide an example?
