### ISSUE TITLE
Improve error messaging when stubbing a non-existent method

### ISSUE THREAD

**Issue by macduy** [Brightify/Cuckoo#129]
Version: 0.8.4

At the moment, when stubbing a non-existent method, the compiler will segfault, e.g.

```swift
protocol Foo {
   func bar() -> Bool // a func, not var
}
```

Test:
```swift
class FooTest: XCTestCase {
   var mockFoo = MockFoo().spy(on: FooStub())
   func setUp() {
      stub(mockFoo) { stub in
         when(mockFoo.bar.get).thenReturn(true)
      }
   }
}
```

does not throw any compiler-time errors, but segfaults instead.

**Comment by TadeasKriz** [comment]
Does it segfault when compiling? If so, it's probably a bug in Swift compiler.

**Comment by macduy** [comment]
Thanks Tadeasz. Most probably yes, I was wondering if this is something other users are experiencing and have complained about. Does the new Stencil-based generation somehow avoid this?

Basically I find that difficult-to-diagnose human errors like these are impediments to adopting an otherwise great framework.

**Comment by TadeasKriz** [comment]
I understand what you mean, but I'm not sure it's something we'll be able to fix/workaround. Does it happen in Swift 3.1 as well? If not, it might be a good idea to send detailed report to http://bugs.swift.org so we can get it fixed in Swift as soon as possible.

**Comment by macduy** [comment]
Gotcha. I'll put together a test project and send it over there.

**Comment by TadeasKriz** [comment]
Thank you very much, you're a superstar!

**Comment by MatyasKriz** [comment]
Hey, it's been a while since this project was filed. I guess we can close it, if this occurs again, feel free to file a new one. Thanks for the report! 🙂
