### ISSUE TITLE
Missing Generics / Template

### ISSUE THREAD

**Issue by igordeoliveirasa** [Brightify/Cuckoo#131]
Is there any way to build GeneratedMocks of classes which use templates/generics?

Original method signature:
func save<T>(_ model: T) throws -> T where T:Object

Generated method signature:
public func save(_ model: T)  throws -> T

Then XCode complains at GeneratedMocks.swift code, like: "Use of undeclared type 'T'".

Thanks in advance..

**Comment by TadeasKriz** [comment]
Hi, 
support for generics is still on our To-Do list for Cuckoo. We're open to PR with that functionality, however we don't have the manpower to implement it ourselves right now.

If you'd be interested in implementing this feature, I'd be more than happy to help you understand Cuckoo's internals :)

**Comment by MatyasKriz** [comment]
Merged!
