### ISSUE TITLE
Autocompletion in Appcode 2017.1

### ISSUE THREAD

**Issue by che1404** [Brightify/Cuckoo#134]
Hi guys, and thank you for this awesome mocking tool.

When I worked on Objective-C projects, one of the main reasons I switched from Xcode to Appcode was the refactoring capabilities. Then when Swift came out, I switched back to Xcode for the same reason. Now I see that Appcode offers some refactoring tools for Swift and I'd like to use it again, but I see that autocompletion in Cuckoo is not working on this IDE. 

Any idea why? Can I do anything to enable autocompletion of cuckoo-generated mocks on Appcode?

Thanks!
Robert.

**Comment by TadeasKriz** [comment]
Hey, thank you for using Cuckoo.

It's weird that the autocompletion doesn't work, because it should. Cuckoo just generates a Swift file with mocks, so if that file is in your `.xcodeproj`, I don't understand why wouldn't the autocompletion work.

**Comment by che1404** [comment]
Yeah, right? Maybe that's an Appcode issue.
The autocopletion problems arises when:
```
when(mock).myFunc().thenDoNothing()
```
The dot after when(mock). doesn't show the available methods in my mocked object.
Strange, right?

**Comment by TadeasKriz** [comment]
Could it be because of generics? Maybe AppCode has a problem with them. Cuckoo relies heavily on generics, so that's the only thing that comes into mind.

**Comment by che1404** [comment]
Yeah, that could explain it.
I'll close this issue for now so that it doesn't bother you guys, ok?
I'll try to find a solution with the Appcode guys.
Thanks again for your awesome tool!

**Comment by TadeasKriz** [comment]
It would be awesome if you could get back to us if you find an answer. Thank you!

**Comment by che1404** [comment]
I found a request on their bug tracker.
This is the specific bug: https://youtrack.jetbrains.com/issue/OC-15264, but seems to be a duplication of: https://youtrack.jetbrains.com/issue/OC-15046.
I hope they'll tackle this soon. Fingers crossed!
In the meantime, back to Xcode again.

**Comment by che1404** [comment]
Hi again!
I just installed the last Appcode (2017.2.3-RC) and the autocompletion problem is still there.
I hope they can fix this by the final release.

Cheers,
Robert.
