### ISSUE TITLE
Xcode 9 beta 2 and Swift 4 compatibility

### ISSUE THREAD

**Issue by che1404** [Brightify/Cuckoo#135]
Hi!
I just downloaded the new Xcode beta 2 build and tried to compile my project using Cuckoo.
I'm getting some errors while launching the post build script. Specifically when it says "Compile Swift Module 'Yams' (13 sources)".

`/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/shims/DispatchOverlayShims.h:68:1: error: use of undeclared identifier 'DISPATCH_SOURCE_TYPE_DATA_REPLACE'
`

**This is not exactly an issue with Cuckoo**, but something you probably want to know in order to give support to the new Xcode and Swift versions. 

Please let us know if we can do anything to help here.

Cheers,
Robert.

**Comment by TadeasKriz** [comment]
@che1404 Thank you for this issue, it'll be great to track the Xcode 9 and Swift 4 compatibility work. Definitely something I'd like to introduce in a branch very soon. I'll check if our dependencies have done the same, if so, I'll try to create that branch for Cuckoo.

**Comment by LucasCFerraz** [comment]
@TadeasKriz , im facing issues with Xcode 9 compatiblity, there is a track to this?

**Comment by kaosdg** [comment]
I've created a PR here:  https://github.com/Brightify/Cuckoo/pull/147

Builds, runs and tests (local) pass
