### ISSUE TITLE
Add support to variadic parameters

### ISSUE THREAD

**Issue by rafaelmaroxa** [Brightify/Cuckoo#140]
Please add support for variadic parameters in the `func` definitions. Right now, the generated code completely ignores the `...` in the parameter definition. This causes the code not to compile, because the generated mock doesn't implement the protocol correctly.

Example:
```
protocol SomeProtocol {
    func someFunction(parameters: T...)
}
```

will yield this in the generated mocks:

```
class MockSomeProtocol: Cuckoo.Mock {
    func someFunction(parameters: T)
}
```

**Comment by TadeasKriz** [comment]
Unfortunately not possible due to missing array splat in Swift. There's no way to override a function with varargs at this time.

**Comment by MatyasKriz** [comment]
I'm not sure if they're about to include the necessary functionality for us to be able to mock variadic parameters soon, so I'll be closing this issue for cleaning purposes.

However, having the `can't fix` tag, I'm sure that when the functionality is added to Swift, we'll include it in Cuckoo.
