### ISSUE TITLE
Property access verification produces compiler warning

### ISSUE THREAD

**Issue by rbeeger** [Brightify/Cuckoo#141]
I have the following
```swift
verify(application).scheduledLocalNotifications.get
```
And the compiler tells me`
Warning:(72, 69) expression of type '__DoNotUse<[UILocalNotification]?>' (aka '__DoNotUse<Optional<Array<UILocalNotification>>>') is unused`

Unfortunately adding `@discardableResult` on `VerifyProperty.get` and `VerifyReadOnlyProperty.get` won't work because it's not available for properties. So replacing `get` with a function `get()` with `@discardableResult` would be an idea. That would break the API, though.

**Comment by TadeasKriz** [comment]
@rbeeger We should be able to add the `get()` method without removing `get` property, shouldn't we? We could mark the `get` as deprecated and the API won't change.

Also, with version 1.0, I'd probably like to remove deprecated methods, so it might be a possibility to change this.

**Comment by gsheld** [comment]
Just came here to second this. I'm in favor of deprecating the property `get` in favor of the method `get()` in order to leverage `@discardableResult`.

**Comment by TadeasKriz** [comment]
I've changed the property to method and added `@discardableResult`. Unfortunately there's no way to have both `get` and `get()` so it's an API-breaking change.

**Comment by gsheld** [comment]
@TadeasKriz Thanks for the update! Appreciate you making the change.

**Comment by TadeasKriz** [comment]
It'll be part of the `0.11.0` build that will be released after we thoroughly test the new spy implementation.

**Comment by MatyasKriz** [comment]
`0.11.0` has been released, so I take it this issue can be closed now. Thanks for the report! 🙂
