### ISSUE TITLE
How to move the generated cuckoo_generator binary

### ISSUE THREAD

**Issue by lmr001** [Brightify/Cuckoo#143]
The problem was that the cuckoo_generator binary was referencing the libCYaml.dylib by an absolute path. I also did not want to download all the dependencies on every build. 

**So I did the following:**

I modified the run and build_generator script see below:
```bash
#!/usr/bin/env bash

pushd Generator
rm -rf .build
env -i PATH="$PATH" HOME="$HOME" swift build
swift build -Xlinker -rpath -Xlinker @executable_path
GENERATOR_BUILD_DIR=$(pwd)
LIBCYAML_FILE=$GENERATOR_BUILD_DIR'/.build/debug/libCYaml.dylib'
install_name_tool -change $LIBCYAML_FILE @rpath/libCYaml.dylib .build/debug/cuckoo_generator
mkdir ../CuckooGenerator
mv .build/debug/cuckoo_generator .build/debug/libCYaml.dylib ../CuckooGenerator
rm -rf .build
popd
```

In the run script, I added CuckooGenerator folder where the cuckoo_generator file will be moved to when the build_generator script is executed.
**FILE_PATH="$SCRIPT_PATH/CuckooGenerator/$FILE_NAME"**

```bash
#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")"
FILE_NAME="cuckoo_generator"
FILE_PATH="$SCRIPT_PATH/CuckooGenerator/$FILE_NAME"

if [[ "$1" = "--clean" || ! -e "$FILE_PATH" ]]; then
    pushd "$SCRIPT_PATH"
	./build_generator
	popd
fi

if [[ "$1" = "--clean" ]]; then
	shift
fi

INPUT_FILES=""
if [[ "$#" > 0 ]]; then
	INPUT_FILES=$(printf '%q ' "$@")
fi

for (( i=0; i<$SCRIPT_INPUT_FILE_COUNT; i++ ))
do
	INPUT_FILE="SCRIPT_INPUT_FILE_$i"
	INPUT_FILES+=" $(printf '%q' "${!INPUT_FILE}")"
done

echo $INPUT_FILES | xargs "$FILE_PATH"
```

**Comment by MatyasKriz** [comment]
Hey, since now Cuckoo is built on our servers and then downloaded from GitHub during pod preparation, I don't think this issue is relevant anymore. If you think otherwise, we can reference it in the `README.md` for developers that get into the same situation you did. Thanks! 🙂
