### ISSUE TITLE
Linking issue with XCode 9 GM

### ISSUE THREAD

**Issue by samskiter** [Brightify/Cuckoo#146]
Looks like there are a couple of issues with running Cuckoo on the latest XCode GM.

The first is it seems to use a static location to find the dynamic libraries it's linked against: /Applications/XCode.app/.../libswiftCore.dylib. The error I get is "dyld: Symbol not found: __TMSS" (in that dylib)

Does cuckoo need to be compiled again, linking against the latest XCode? I've noticed that Swiftgen actually bundles libswiftCore.dylib along as a dependency when adding via pods.

**Comment by ptsimpso** [comment]
Did you resolve this?

**Comment by TadeasKriz** [comment]
Hey, sorry for my late response. Is this still valid with the new `0.10.0` version? I wasn't able to reproduce this. Please let us know how to reproduce this. Thanks!

**Comment by samskiter** [comment]
We had to recompile the dylibs

**Comment by TadeasKriz** [comment]
Oh, that's right. You can't (well, shouldn't) use binaries compiled with one version of Swift compiler in a runtime with another version.

**Comment by samskiter** [comment]
@TadeasKriz I mean that in order to fix the issue we had to recompile. Seems that the dylibs ship with Cuckoo and are compiled on an older version

**Comment by MatyasKriz** [comment]
Does this issue still occur for you with the 0.11.1 version of Cuckoo?

**Comment by samskiter** [comment]
Unsure, will have to get back to you soon. Will let my team know it may be fixed
