### ISSUE TITLE
Many errors generating code with Xcode 9

### ISSUE THREAD

**Issue by bsarrazin** [Brightify/Cuckoo#148]
``` 
SWXMLHash.XMLIndexer:72:22: error: invalid redeclaration of 'Element'
``` 
```
Carthage/Checkouts/Cuckoo/Generator/.build/checkouts/FileKit.git-2495357206000708207/Sources/FileSystemWatcher.swift:38:64: error: C function pointer signature '(ConstFSEventStreamRef, UnsafeMutableRawPointer?, Int, UnsafeMutableRawPointer, UnsafePointer<FSEventStreamEventFlags>?, UnsafePointer<FSEventStreamEventId>?) -> Void' (aka '(OpaquePointer, Optional<UnsafeMutableRawPointer>, Int, UnsafeMutableRawPointer, Optional<UnsafePointer<UInt32>>, Optional<UnsafePointer<UInt64>>) -> ()') is not compatible with expected type 'FSEventStreamCallback' (aka '@convention(c) (OpaquePointer, Optional<UnsafeMutableRawPointer>, Int, UnsafeMutableRawPointer, UnsafePointer<UInt32>, UnsafePointer<UInt64>) -> ()')
```
```
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/ben/Development/Projects/[redacted]/[redacted]/Carthage/Checkouts/Cuckoo/Generator/.build/debug.yaml main
```
```
xargs: /Users/ben/Development/Projects/[redacted]/[redacted]/Carthage/Checkouts/Cuckoo/Generator/.build/debug/cuckoo_generator: No such file or directory
```

Is this a known issue?

**Comment by kaosdg** [comment]
There are a lot of dependencies that need to be updated in the Package.swift spec.

I'm working on my [own branch](https://github.com/kaosdg/Cuckoo/tree/swift-4.0) right now and have gotten pretty far - the tools and framework compile.  

That said, the generated mocks are not correct for the new [closure changes in Swift 4.0](https://github.com/apple/swift-evolution/blob/master/proposals/0110-distingish-single-tuple-arg.md) so I'm working through that.

seeing this error: 
```
Cuckoo/Tests/Generated/GeneratedMocks.swift:544:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (String, ((String) -> Void)?), original: ((String, ((String) -> Void)?) -> ())?)'
```


Here's more on the closure changes, and some really concerning issues around it:
https://lists.swift.org/pipermail/swift-evolution-announce/2017-June/000386.html 
(and if you really want to go down the rabbit hole: https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20170522/036844.html )

cc: @TadeasKriz @FilipDolnik @nxtstep

**Comment by bsarrazin** [comment]
@kaosdg that's awesome!
I'm trying to gauge the ability for our team to move to Xcode 9 and Swift 4. Have you been successful in adding Swift 4 compatibility?

**Comment by kaosdg** [comment]
@bsarrazin Having a bit of trouble w/ the closure changes, specifically around non-escaping closures.

Seems that with the new way to write closures in swift, we HAVE to capture them:
```
return cuckoo_manager.call("withClosure(_: (String) -> Int) -> Int",
            parameters: (closure),
            original: observed.map { o in
                return { (args) -> Int in
                    let (closure) = args
                    return o.withClosure(closure)
                }
            })
```
which yields the error:  `Non-escaping parameter 'args' may only be called` on the `let (closure) = args` line.

I can change this to:
```
return cuckoo_manager.call("withClosure(_: (String) -> Int) -> Int",
            parameters: (closure),
            original: observed.map { o in
                return { (args) -> Int in
                    return o.withClosure(args)
                }
            })
```
and that "works" (compiles without error)

however in mocked functions with multiple parameters where one (or more) parameters are a non-escaping closure thing get more difficult:

```
func withClosureAndParam(_ a: String, closure: (String) -> Int)  -> Int {
        
        return cuckoo_manager.call("withClosureAndParam(_: String, closure: (String) -> Int) -> Int",
            parameters: (a, closure),
            original: observed.map { o in
                return { (args) -> Int in
                    return o.withClosureAndParam(args.0, closure: args.1)
                }
            })
        
    }
```
which results in the same error  `Non-escaping parameter 'args' may only be called` but now on the `parameters: (a, closure)` line.

I suspect this has a lot to do with the MockManager methods and I have PROBABLY adjusted them wrong for Swift 4.

**Comment by bsarrazin** [comment]
@kaosdg even without supporting Swift 4 right away, what about supporting Xcode 9 with Swift 3.2 at first, and then move on to supporting Swift 4?

**Comment by TadeasKriz** [comment]
@kaosdg Hey, not sure if you tried this, but it should work for those closures.

There is this method in Swift: `withoutActuallyEscaping(closure: (T) -> U, do: @escaping (T) -> U)`. You can wrap these because they don't really escape with Cuckoo, we just have to tell the compiler explicitly using this function.

**Comment by kaosdg** [comment]
@bsarrazin I think that should be do-able as well - that part is simply updating the Generator dependencies so they can be built properly via command line

Of course you'd have to ensure that the Cuckoo sources and generated mocks are still compiled with swift 3.2 within your project / test target.

That said, with @TadeasKriz's direction I just re-opened a PR for full Swift 4 support :  https://github.com/Brightify/Cuckoo/pull/149
I feel like how I implemented `withoutActuallyEscaping(_:do:)` is pretty ugly but it works right now.

Hopefully this covers it - the unit tests pass locally, but I havent' had a chance to integrate it into my current project yet to see if I missed anything.

**Comment by EvsenevDev** [comment]
@kaosdg will you merge you branch into main repo?

**Comment by bsarrazin** [comment]
@EvsenevDev we've been having a bit of a discussion in the Cuckoo Slack team (http://swiftkit.brightify.org/) and it seems like @TadeasKriz is looking into switching over to Sourcery (https://github.com/krzysztofzablocki/Sourcery) for generating templates. I do not know if this PR will merged at this point.

**Comment by TadeasKriz** [comment]
@bsarrazin I'm just doing a review of this PR and it will be merged after I review it. Switch to Sourcery will not be immediate I'm affraid.

**Comment by bsarrazin** [comment]
@TadeasKriz ok that's great. As long as we can move forward while you review the Sourcery option.

**Comment by gsheld** [comment]
I noticed the fixes are in master now. Will there be a new release soon?

**Comment by TadeasKriz** [comment]
@gsheld Yes, a new release is coming tomorrow.

**Comment by TadeasKriz** [comment]
@gsheld Version 0.10.0 is out! Huge thanks to @kaosdg for this release!

**Comment by gsheld** [comment]
@TadeasKriz Thanks for letting me know! @kaosdg you're the real mvp.

**Comment by kaosdg** [comment]
awesome!  i guess we can close this issue?

**Comment by TadeasKriz** [comment]
Hopefully this is resolved. If not, feel free to reopen.
