### ISSUE TITLE
Empty Parameters Build Issue (Xcode 9, Swift 4)

### ISSUE THREAD

**Issue by alex-king-ck** [Brightify/Cuckoo#150]
Hello,

I'm running into a build issue since upgrading to Xcode 9 and Swift 4. I'm receiving a compiler error for mocked methods with no parameters:

```swift
func cancelPressed()  {
        
        return cuckoo_manager.call("cancelPressed()",
            parameters: (),
            original: observed.map { o in
                return { () in
                    o.cancelPressed()
                }
            })
        
    }
```
needs to be:
```swift
func cancelPressed()  {
        
        return cuckoo_manager.call("cancelPressed()",
            parameters: (),
            original: observed.map { o in
                return { (_) in
                    o.cancelPressed()
                }
            })
        
    }
```
Please let me know if there's a way around this or if a fix will be made.

**Comment by TadeasKriz** [comment]
Hey, please try the new version `0.10.1` and let me know if this is still causing problems. We have empty-parameter methods in tests and they work so if it still won't work for you, something else might need to be fixed. Thanks!

**Comment by AdamMak** [comment]
How do you install 0.10.1? I installed via cocapods and it is installing version 0.9.2

**Comment by TadeasKriz** [comment]
@AdamMak You probably have to call `pod update Cuckoo`. It should update just the Cuckoo's version and not other libraries.

**Comment by AdamMak** [comment]
Cheers that seems to work
