### ISSUE TITLE
Issue with named tuples

### ISSUE THREAD

**Issue by andlang** [Brightify/Cuckoo#152]
Hi,

with the release 0.10.0 (btw. thank you for the swift 4 support) I get an error for stubs of protocols with named tuples:

**Protocol:**
```swift
func withNamedTuple(tuple: (a: String, b: String)) -> Int
```

**Test code:**
```swift
func testWithNamedTuple() {
    stub(mock) { mock in
       when(mock.withNamedTuple(tuple: any())).thenReturn(0)
    }
    XCTAssertEqual(mock.withNamedTuple(tuple: (a: "foo", b: "bar")), 0)
}
```

**Assertion Error:**
```
XCTAssertEqual failed: throwing "No stub for method `withNamedTuple(tuple: (a: String, b: String)) -> Int` using parameters ("foo", "bar") and no original implementation was provided."
```

With 0.9.2 this worked.

Is this a known issue?

**Comment by TadeasKriz** [comment]
Hey, I changed the signature a bit and tried adding a method just like yours and it works. Please try the latest version `0.10.1` and let us know. Thanks!

**Comment by andlang** [comment]
Great! Thank you very much. Everything works now.
