### ISSUE TITLE
Build script not working

### ISSUE THREAD

**Issue by AdamMak** [Brightify/Cuckoo#153]
I am trying to get this cuckoo framework working but I am having an issue getting the build script to work. Here is the build script

```
# Define output file. Change "$PROJECT_DIR/Tests" to your test's root source folder, if it's not the default name.
OUTPUT_FILE="$PROJECT_DIR/Tests/GeneratedMocks.swift"
echo "Generated Mocks File = $OUTPUT_FILE"

# Define output file. Change "$PROJECT_DIR/Tests" to your test's root source folder, if it's not the default name.
OUTPUT_FILE="$PROJECT_DIR/Tests/GeneratedMocks.swift"
echo "Generated Mocks File = $OUTPUT_FILE"

# Define input directory. Change "$PROJECT_DIR" to your project's root source folder, if it's not the default name.
INPUT_DIR="$PROJECT_DIR"
echo "Mocks Input Directory = $INPUT_DIR"

# Generate mock files, include as many input files as you'd like to create mocks for.
${PODS_ROOT}/Cuckoo/run generate --testable "$PROJECT_NAME" \
--output "${OUTPUT_FILE}" \
"$INPUT_DIR/Objects/Person.swift" \
# ... and so forth

# After running once, locate `GeneratedMocks.swift` and drag it into your Xcode test target group.
```

However when I run the script, I get 30 warnings and the following error

> ~/Desktop/CuckooFun/Pods/Cuckoo
> ~/Desktop/CuckooFun
> Could not read contents of `/Users/admin/Desktop/CuckooFun/Objects/Person.swift`
> FileKitError(Could not write to file at "/Users/admin/Desktop/CuckooFun/Tests/GeneratedMocks.swift")
> Command /bin/sh failed with exit code 1
> 

Any ideas what is causing this?

**Comment by TadeasKriz** [comment]
Is this a valid path: `/Users/admin/Desktop/CuckooFun/Objects/Person.swift` with the source file? And is the output path: `/Users/admin/Desktop/CuckooFun/Tests/GeneratedMocks.swift` valid?

**Comment by AdamMak** [comment]
![screenshot](https://user-images.githubusercontent.com/17201601/31668581-7e339d38-b34a-11e7-96d1-ff0b85d2ef4a.png)

You can see my project structure here. As you can see, that is a valid path to the Person.swift class. And as for GeneratedMock, is that not meant to be auto generated after the script is run?

**Comment by TadeasKriz** [comment]
Yes, but the directory has to exist. Try changing these two paths to this:
`/Users/admin/Desktop/CuckooFun/CuckooFun/Objects/Person.swift`
`/Users/admin/Desktop/CuckooFun/CuckooFunTests/GeneratedMocks.swift`

It should work.

**Comment by AdamMak** [comment]
Where do I change this? These paths are generated by the build script? So do I need to change my build script?

**Comment by AdamMak** [comment]
That seems to fix it, cheers for your help!!
