### ISSUE TITLE
Issue with the verify times method

### ISSUE THREAD

**Issue by AdamMak** [Brightify/Cuckoo#154]
I am trying to verify that a certain method has been called in order to effectively unit test my class, but the verify function keeps saying the method has not been invoked. Example of my class below

> class Person: NSObject {
> 
>     override init() {
> 
>     }
>     
>     func testing()
>     {
>         methodA()
>     }
> 
>     func methodA()
>     {
>         print("Method a called")
>     }
>     
>     func methodB()
>     {
>         print("method b called")
>     }
> }
> 

So when testing method is called, it should call methodA. So I have setup a unit test to try this

>     func testFunctionCall()
>     {
>         let mock = MockPerson().spy(on: Person())
>      
>          stub(mock) { (mock) in
>             when(mock.testing()).thenDoNothing()
>         }
> 
>         verify(mock, times(1)).methodA()
>     }
> 

However, test is failing with error saying methodA has not been invokved? Could someone tell me what I am doing wrong here? 

Thanks in advance

**Comment by TadeasKriz** [comment]
Hi @AdamMak. There are three problems. In your testing code, you stubbed the `testing` method to do nothing. So when it's called, it will just track the call, but won't do anything else. What you were looking for was probably `.thenCallRealImplementation()`. Second thing is that you don't call the `testing` method. Your code has to call it between the end of `stub` and start of `verify`.

Third problem is that Cuckoo didn't support tracking calls inside the instance you spy on. Please try the latest commit from `master` branch and let me know if it works for you. You'll have to change the test code a bit to:

```
    let mock = MockPerson().withEnabledSuperclassSpy()
 
     stub(mock) { (mock) in
        when(mock.testing()).thenCallRealImplementation()
    }

    mock.testing()

    verify(mock, times(1)).methodA()
```

**Comment by pmartens-medicfp** [comment]
**Hello @TadeasKriz, I'm also having this issue:
Here's a snippet of the original class;**

class DeviceLocationPresenter: DeviceLocationContractPresenter {
    init(_ view: DeviceLocationContractView, locationService: LocationService?) {
        self.view = view
        self.locationService = locationService
    }

    func actionFor(title: String) -> UIAlertAction? {
        if title == Properties.Alerts.Options.logout {
            return logoutAction()
        } else if title == Properties.Alerts.Options.retry {
            return retryAction()
        } else if title == Properties.Alerts.Options.settings {
            return settingsAction()
        }
        return nil
    }
    
    func logoutAction() -> UIAlertAction {
        return UIAlertAction(title: Properties.Alerts.Options.logout, style: .destructive) { action in
            AuthenticationService.sharedInstance.logout()
        }
    }
    
    func retryAction() -> UIAlertAction {
        return UIAlertAction(title: Properties.Alerts.Options.retry, style: .default) { action in
            self.locationService?.getUserLocation(callback: self)
        }
    }
    
    func settingsAction() -> UIAlertAction {
        return UIAlertAction(title: Properties.Alerts.Options.settings, style: .default, handler: { action in
            if let appSettings = URL(string: UIApplicationOpenSettingsURLString) {
                UIApplication.shared.open(appSettings, options: [:], completionHandler: nil)
            }
        })
    }
}

**For testing I've tried a number of variations of the following:**

func test_should_callLogoutAction_when_showAlertCalled() {
        view = MockDeviceLocationView()
        presenter = DeviceLocationPresenter(view, locationService: nil)
        let testPresenter = MockDeviceLocationPresenter(view, locationService: nil).spy(on: presenter)
        stub(testPresenter) { (mock) in
            when(mock.actionFor(title: Properties.Alerts.Options.logout)).thenCallRealImplementation()
        }
        stub(testPresenter) { (mock) in
            when(mock.logoutAction()).thenCallRealImplementation()
        }
        
        _ = testPresenter.actionFor(title: Properties.Alerts.Options.logout)

        verify(testPresenter).logoutAction()
    }

**When trying the withEnabledSuperclassSpy method that you mentioned I'm getting a compiler error saying the member doesn't exist. It should be the latest version, as I just installed Cuckoo yesterday.**

**Comment by TadeasKriz** [comment]
The withEnabledSuperclassSpy method is only in the master branch. Please try specifying the repository and branch in your Podfile to test this.

**Comment by pmartens-medicfp** [comment]
Was able to get it working with explicitly declaring to pull the master branch, thanks.

**Comment by MatyasKriz** [comment]
Can we consider this issue resolved, @pmartens-medicfp ? 🙂
