### ISSUE TITLE
Mock file is not created

### ISSUE THREAD

**Issue by simformsolutions** [Brightify/Cuckoo#156]
Mock files are not generated, here is the screenshot of my Run Script:-
http://prntscr.com/h5qqr1

Any help would be appreciated.

**Comment by TadeasKriz** [comment]
@simformsolutions Hi, did you use the run script from Readme?

**Comment by poojaagarwal1331** [comment]
Yes I did that here it is:-
#Generate mock files, include as many input files as you’d like to create mocks for.
${PROJECT_DIR}/Carthage/Checkouts/Cuckoo/run generate —output “$PROJECT_DIR/leopardTests/mocks”


Input file:-
$(PROJECT_DIR)/leopard/domain/device/BeartoothDevice.swift

**Comment by simformsolutions** [comment]
Yes I did that here it is:-
#Generate mock files, include as many input files as you’d like to create mocks for.
${PROJECT_DIR}/Carthage/Checkouts/Cuckoo/run generate —output “$PROJECT_DIR/leopardTests/mocks”

Input file:-
$(PROJECT_DIR)/leopard/domain/device/BeartoothDevice.swift

**Comment by simformsolutions** [comment]
Any update?

**Comment by TadeasKriz** [comment]
Hey, it should work, what error are you seeing in Xcode?

**Comment by simformsolutions** [comment]
Its working fine when I use PODS, but when used with Carthage its not working fine.
Script is running but not creating the respective file.

**Comment by TadeasKriz** [comment]
Do you see any error in the build output? Could you show me what's the build output from the `Run script` phase?

**Comment by simformsolutions** [comment]
@TadeasKriz  Its resolved now.
Thank you!

**Comment by TadeasKriz** [comment]
What was the problem? I'd like to know so we have more information next time.

**Comment by simformsolutions** [comment]
Actually, there was issue in getting framework path, when we create "Copy files" from "Build phase" of Test Target.
