### ISSUE TITLE
Support for nested classes [Feature request]

### ISSUE THREAD

**Issue by msewell** [Brightify/Cuckoo#159]
It is common to nest classes for namespacing reasons:

```
// In Outer.swift

class Outer {
    // ...

    class Inner {
        // ...
    }
}
```

Currently, Cuckoo will generate `MockOuter` from Outer.swift, but not `MockInner` (well, `MockOuter.MockInner`). This is a bit of a bummer, since developers will have to either write `MockInnner` themselves, or move `Inner` to the same level as `Outer` in their production code to allow for automated mock generation through Cuckoo, thus negating the benefits of namespacing and polluting the top-level namespace.

Is there a reason Cuckoo cannot generate `MockInner` as well as `MockOuter`? This is a feature I'd really like to see!

**Comment by michaelom** [comment]
Same problem here. 

Having to workaround this limitation is tedious.

**Comment by karan-sankey** [comment]
Also I want to know if there is support for class which inherit from another class(multiple inheritance of class in linear manner).
