### ISSUE TITLE
Build error when using Carthage and Xcode 9.3 beta

### ISSUE THREAD

**Issue by masterjefferson** [Brightify/Cuckoo#166]
**Xcode:** 9.3 beta, build 9Q98q (which includes Swift 4.1)
**Carthage**: 0.27.0

Carthage fails when building Cuckoo with Swift 4.1. The build output is attached.

[cuckoo-build-failure.log](https://github.com/Brightify/Cuckoo/files/1672179/cuckoo-build-failure.log)

**Comment by brianoqr** [comment]
goto to the directory wher the library is. make sure youhave the latest version 0.11.1 or something. run the build_generator command. take the newly built generator from the .build/..../realeas dir.  copy it over the generator in the lib root. this fixed it for me. the library has default a generator build in swift 4.0, which is the reason for the errors. you just need to rebuild it in 4.1

**Comment by brianoqr** [comment]
btw your error look lik you are using version 0.9 or so, with 0.11.1 you get an error regard swiftcore which makes the issue clearer

**Comment by TadeasKriz** [comment]
@masterjefferson Please try version `0.11.2` if it works for you.

**Comment by MatyasKriz** [comment]
Assuming the thumb ups mean that everything's working, I'm closing this one. Thanks for the report!

**Comment by masterjefferson** [comment]
yes, thanks!
