### ISSUE TITLE
Generated import of module is wrong

### ISSUE THREAD

**Issue by Hatko** [Brightify/Cuckoo#168]
I have different target name and project name. Still, Cuckoo generates 
`@testable import ProjectName` 
So code can't be compiled.
Can this somehow be fixed?

**Comment by benniebotha** [comment]
Specify the module name of the target explicitly then.
Change this line of the generator script:
`"${PODS_ROOT}/Cuckoo/run" generate --testable "$PROJECT_NAME" \`
to
`"${PODS_ROOT}/Cuckoo/run" generate --testable "YOUR_CUSTOM_MODULE_NAME" \`

That should change the import statement generated.

**Comment by MatyasKriz** [comment]
Hey, @benniebotha thanks for the tip here. @Hatko, have you tried if that works for you? 🙂
