### ISSUE TITLE
Create mocks for all protocols/classes in project

### ISSUE THREAD

**Issue by armintelker** [Brightify/Cuckoo#171]
As far as I understand the documentation

```
# Generate mock files, include as many input files as you'd like to create mocks for.
${PODS_ROOT}/Cuckoo/run generate --testable "$PROJECT_NAME" \
--output "${OUTPUT_FILE}" \
"$INPUT_DIR/FileName1.swift" \
"$INPUT_DIR/FileName2.swift" \
"$INPUT_DIR/FileName3.swift"
# ... and so forth
````

you need to add for all classes/protocols you want to mock a extra entry in the run script.
Is there a possibility to recursively create mocks for all protocols/classes in a folder or all files that are matching a regex pettern...

This is not a scalable solution if your project grows. 

Did i missed something in the documentatoin?

Thanks

**Comment by iadcialim** [comment]
@MatyasKriz @armintelker So how to do this?

**Comment by iadcialim** [comment]
After tracing, can do like this: https://github.com/Brightify/Cuckoo/pull/215/files
