### ISSUE TITLE
Generating mocks takes too much time

### ISSUE THREAD

**Issue by nasakinmaxim** [Brightify/Cuckoo#172]
Is it just me or CuckooGenerator is just slow? Is there any way to use Sourcery for generating mocks and Cuckoo for using them?

**Comment by MatyasKriz** [comment]
Did the prebuilt generator help with this issue? 🙂

**Comment by nasakinmaxim** [comment]
Yes, it did! It's now 3 times faster on CI. 💁‍♂️

**Comment by MatyasKriz** [comment]
Glad to hear that. 👍

**Comment by aramark-pivotal** [comment]
I noticed that if you mark things correctly as private, fileprivate, and internal the process is much faster.  Less code is generated.
