### ISSUE TITLE
Error Generic parameter 'F' could not be inferred

### ISSUE THREAD

**Issue by vinyguitar** [Brightify/Cuckoo#176]
Hi guys, I'm having this error when I try to mock this function.

`let mockBIUserDefaults = MockBIUserDefaults()
        stub(mockBIUserDefaults) { (stub) in
            when(stub.get(key: "", defaultValue: 0))
        }`

This error point the when line, I don't know what is wrong, this is the class that I'm trying to mock

`public func get(key: String, defaultValue: Any) -> Any {
        return userDefaults.object(forKey: key) ?? defaultValue
    }`

and this is the generated stub method...

`func get<M1: Cuckoo.Matchable, M2: Cuckoo.Matchable>(key: M1, defaultValue: M2) -> Cuckoo.StubFunction<(String, Any), Any> where M1.MatchedType == String, M2.MatchedType == Any {
            let matchers: [Cuckoo.ParameterMatcher<(String, Any)>] = [wrap(matchable: key) { $0.0 }, wrap(matchable: defaultValue) { $0.1 }]
            return .init(stub: cuckoo_manager.createStub("get(key: String, defaultValue: Any) -> Any", parameterMatchers: matchers))
        }`

**Comment by vinyguitar** [comment]
I'll attach the screenshots as the code that I put there is kind hard to read...

![screen shot 2018-03-13 at 12 21 16](https://user-images.githubusercontent.com/1063897/37351191-46294018-26b9-11e8-9651-9b1342ce7252.png)

![screen shot 2018-03-13 at 12 21 35](https://user-images.githubusercontent.com/1063897/37351215-53dc15dc-26b9-11e8-89c8-a60744d76446.png)

![screen shot 2018-03-13 at 12 21 46](https://user-images.githubusercontent.com/1063897/37351228-5ad5126c-26b9-11e8-8e35-c987ce599772.png)

**Comment by TadeasKriz** [comment]
It's caused by `Any` which is not possible to compare. Try:
```
when(stib.get(key: "", defaultValue: any()))
```

**Comment by vinyguitar** [comment]
Nice, that worked! Thanks!!
