### ISSUE TITLE
thenReturn(_: , _:) fails in some cases

### ISSUE THREAD

**Issue by davidevincenzi** [Brightify/Cuckoo#177]
Consider the following two cases:

First
```
var closure: ((SomeClass) -> Void)?
stub(myMock) { (stub) in
    when(stub.didSelect.set(any())).then({ (cls) in
        closure = cls
    })
    when(stub.didSelect.get).then({ () -> ((SomeClass) -> Void)? in
        return closure
    })
}
```

Second
```
var closure: ((SomeClass) -> Void)?
stub(myMock) { (stub) in
    when(stub.didSelect.set(any())).then({ (cls) in
        closure = cls
    })
    when(stub.didSelect.get).thenReturn(closure)
}
```

The second one fails to return the closure when something asks for it.

**Comment by MatyasKriz** [comment]
Could you please tell me what type the second case return? Is it just `Void`?

**Comment by davidevincenzi** [comment]
It returns `nil`. It goes into `case .returnValue(let value)` inside `callThrowsInternal` but value is `nil`.

**Comment by MatyasKriz** [comment]
Hey, I just tried to reproduce this with the latest version and couldn't do so, perhaps we fixed it somewhere along the way. I'll close this issue, but if the issue persists, feel free to reopen it.
