### ISSUE TITLE
Can Cuckoo mock/stub system libraries?

### ISSUE THREAD

**Issue by houmie** [Brightify/Cuckoo#180]
I'm very interested to know if Cuckoo can stub/mock system libraries as well?

for example can it mock `NEVPNConnection` in `NetworkExtension`?

Or is it designed to only generate stubs from my own classes and not system classes?

If yes, is there any code example to demonstrate this? I can't find anything.

Many Thanks,

**Comment by exevil** [comment]
+1 here.

**Comment by MatyasKriz** [comment]
Hey there, along with @TadeasKriz we added an experimental ObjC mocking functionality that utilizes OCMock using much neater API that Swift provides along with all the safety that Swift can offer.

This should allow for mocking all objects from ObjC, along with the system libraries. Feel free to try the `experimental/objectiveC` branch and post any issues or proposals to PR #290. Thanks in advance!
