### ISSUE TITLE
pod install fails when the environment variable $GREP_OPTIONS has --with-filename  

### ISSUE THREAD

**Issue by ecoopnet** [Brightify/Cuckoo#183]
We encountered the problem that we never can install Cuckoo 0.11.0 in specific machine.
 ```
# pod install --verbose
Installing Cuckoo (0.11.0)
[!] /bin/bash -c
set -e
curl -Lo cuckoo_generator `curl "https://api.github.com/repos/Brightify/Cuckoo/releases/tags/0.11.0" | grep -oe '"browser_download_url": *"[^" ]*"' | grep -oe 'http[^" ]*' | grep cuckoo_generator | head -1`

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5478  100  5478    0     0   8310      0 --:--:-- --:--:-- --:--:--  8300
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: (standard
curl: (3) Port number ended with ':'
curl: (3) [globbing] bad range in column 12
```

finally i found solution. the command:
> curl "https://api.github.com/repos/Brightify/Cuckoo/releases/tags/0.11.0" | grep -oe '"browser_download_url": *"[^" ]*"' | grep -oe 'http[^" ]*' | grep cuckoo_generator | head -1
returned storange header like below on the machine.
> (standard input):1:(standard input):1:https://github.com/Brightify/Cuckoo/releases/download/0.11.0/cuckoo_generator

It is occured by this environment variable.

> export GREP_OPTIONS='--color=always --with-filename --line-number'

When ` --with-filename` was set in `$GREP_OPTIONS`, Cuckoo installation always failed.
After override GREP_OPTION with empty value ( `export GREP_OPTIONS=` ), the problem was resolved.

**Comment by MatyasKriz** [comment]
Hey, thanks for the issue report! I didn't notice grep had something like this. Will using `export GREP_OPTIONS=` override the env var only during the script, or is there a need to save the current contents and then restore them after the script is done?

**Comment by TadeasKriz** [comment]
We should be able to just do:

```
GREP_OPTIONS="" curl -Lo cuckoo_generator `curl "https://api.github.com/repos/Brightify/Cuckoo/releases/tags/0.11.0" | grep -oe '"browser_download_url": *"[^" ]*"' | grep -oe 'http[^" ]*' | grep cuckoo_generator | head -1`
```

**Comment by MatyasKriz** [comment]
Now I hope `curl` and `head` don't have similar options..

**Comment by ecoopnet** [comment]
Thanks @TadeasKriz to merge my pull request so quickly.
I am very glad to contribute to Cuckoo!
