### ISSUE TITLE
cuckoo_generator  not support Xcode 9.3  ?

### ISSUE THREAD

**Issue by dimsky** [Brightify/Cuckoo#188]
dyld: Symbol not found: __T0SS13CharacterViewVN
  Referenced from: /Users/.../cuckoo_generator
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /Users/..././cuckoo_generator
[1]    58302 abort      ./cuckoo_generator generator

**Comment by TadeasKriz** [comment]
Please try version `0.11.2` if it works for you.

**Comment by dimsky** [comment]
Newbility, tks.

**Comment by kainjow** [comment]
I got this error with 0.11.3 on Xcode 9.4.1. I reran `build_generator` then replaced the existing `cuckoo_generator` with the new one in `./Generator/.build/x86_64-apple-macosx10.10/release/cuckoo_generator`.
