### ISSUE TITLE
Implicit behavior via Stubs?

### ISSUE THREAD

**Issue by adotor** [Brightify/Cuckoo#189]
The following suggestion in the README does not work with the new spy-API anymore.

> Stubs can be used to set implicit (no) behavior to mocks without the need to use thenDoNothing() like this: MockGreeter().spy(on: GreeterStub()).

Is there another way to achieve this now?

**Comment by macduy** [comment]
Hi @adotor was wondering if you found a workaround for this?

**Comment by macduy** [comment]
Hey @adotor Tadeas has kindly made a change that re-enables the behaviour. Check it out here: https://github.com/Brightify/Cuckoo/pull/205
