### ISSUE TITLE
Add support for cuckoo.yml configuration file

### ISSUE THREAD

**Issue by TadeasKriz** [Brightify/Cuckoo#200]
We should add a support for configuring Cuckoo generator with YAML file (using [Yams](https://github.com/jpsim/Yams)). This will make it easier to configure and run the generator as well as adding new files to mock.

**Comment by bsarrazin** [comment]
@TadeasKriz [Sourcery](https://github.com/krzysztofzablocki/Sourcery) already supports this.
If you are thinking of spending time into this, I would suggest spending time to see if you can drop the generator in favour of Sourcery.

**Comment by TadeasKriz** [comment]
My thinking was just adding a simple file with the configuration that's normally passed in through parameters. So that's a minimal change compared to replacing the whole Cuckoo Generator with Sourcery.

Again, I'm not opposed to replacing the Generator with Sourcery, but it's a huge change for our team to implement. And that simply outweighs any possible benefits it might bring.

**Comment by bsarrazin** [comment]
If you remove the templates from the compiled generator and load them at runtime, I might be able to find some time eventually to do a PR for this.

**Comment by TadeasKriz** [comment]
@bsarrazin I'm not sure if I understand the replacement of generator correctly. Do you mean we would completely remove Cuckoo generator binary and just use Sourcery binary with a template? If that's the case, why do you need to move the templates from compiled to runtime?

**Comment by SaezChristopher** [comment]
Honnestly its a good idea to create yml, better than do nothing and we will be not force to use sourcery.

**Comment by MatyasKriz** [comment]
Cuckoofile supersedes this.
