### ISSUE TITLE
Add swift_version 4.0 to podspec to work in Swift 3.x projects.

### ISSUE THREAD

**Issue by alexey-bondar** [Brightify/Cuckoo#201]
Adding swift_version will instruct CocoaPods to set the `SWIFT_VERSION` build setting of Cuckoo without the need to set it manually (see workaround for the manual setup).

## Workaround

Before the swift_version is set in the podspec, it can be workarounded by adding the following snippet to your Podfile.

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Cuckoo'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```

**Original issue**:

> ## callInternal is inaccessible due to private protection level

> After updating to the latest version 0.11.3 I've got build failure (our current swift version is 3.2):
> 
> [07:48:22][Step 3/4] ❌  /Users/teamcity/buildAgent/work/34229a4915d27197/teesnap-ios/Pods/Cuckoo/Source/MockManager.swift:169:16: 'callInternal' is inaccessible due to 'private' protection level
> [07:48:22][Step 3/4] return callInternal(method, parameters: parameters, superclassCall: superclassCall)
> [07:48:22][Step 3/4] ❌  /Users/teamcity/buildAgent/work/34229a4915d27197/teesnap-ios/Pods/Cuckoo/Source/MockManager.swift:235:20: 'callThrowsInternal' is inaccessible due to 'private' protection level
> [07:48:22][Step 3/4] return try callThrowsInternal(method, parameters: parameters, superclassCall: superclassCall)
> 
> Do you have any plans on supporting Swift 3.2/3.3?

**Comment by TadeasKriz** [comment]
Hi, could you set the build setting `SWIFT_VERSION` to `4.0` for Cuckoo? We will add the property added in CocoaPods 1.4.0 in the next release so this should hopefully be set for you.

**Comment by alexey-bondar** [comment]
Hi, unfortunately I can't as our CI servers are using Xcode 9.2 (Swift 3.2). 
So in that case I will downgrade the pod's version and wait for your fix.

**Comment by TadeasKriz** [comment]
Xcode 9.2 has Swift 4.0 though, doesn't it?

**Comment by alexey-bondar** [comment]
Thanks for a peace of advice, it solves the build failure:

```
if target.name == 'Cuckoo'
    target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
    end
end
```
