### ISSUE TITLE
Carthage/Checkouts/Cuckoo/cuckoo_generator: No such file or directory

### ISSUE THREAD

**Issue by Hatko** [Brightify/Cuckoo#203]
`cuckoo_generator` is missing in the Cuckoo directory when running Travis.

I'm not sure if it's a Cuckoo related issue but during debug mode, I found all the content of the directory except `cuckoo_generator`. 

I'm using Carthage and Cuckoo 0.11.3

**Comment by MatyasKriz** [comment]
Hey there. The `run` script in your build phases prints this message that it can't find the `cuckoo_generator`?
