### ISSUE TITLE
Symbol-specific import statements are missing in generated Mock file, leading to compile errors

### ISSUE THREAD

**Issue by msewell** [Brightify/Cuckoo#204]
(Observed in Cuckoo 0.11.3.)

[Symbol-specific import statements](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Declarations.html#//apple_ref/swift/grammar/import-declaration) in a source file are missing in its generated Mock file.

Example source file (`MyClass.swift`):
```swift
import struct Foundation.Decimal

class MyClass {
    let decimal: Decimal
    
    init(decimal: Decimal) {
        self.decimal = decimal
    }
}
```

Generated mock file (`MockMyClass.swift`) (excerpt):
```swift
...
import Cuckoo
import struct // <- Line leads to compilation error. Expected: `import struct Foundation.Decimal`

class MockMyClass: MyClass, Cuckoo.ClassMock {
    typealias MocksType = MyClass
...
```

**Comment by msewell** [comment]
Without having looked too closely at `CuckooGenerator`'s source to confirm it, my guess is that this is an issue with the Stencil template used to generate mock files.

**Comment by MatyasKriz** [comment]
Nope! This one is on us, sorry! Should be up in the next version.
