### ISSUE TITLE
Handle Mocking protocols with Associated types & generics

### ISSUE THREAD

**Issue by samskiter** [Brightify/Cuckoo#206]
I have a protocol I want to mock - problem is it has associated types and generics

something like:

```
protocol MyProtocol {

    associatedtype MyGeneric: Equatable

    func doSomething(with thing: SomeStruct<MyGeneric>)
}
```

When generating a mock for this, Cuckoo generates code that won't compile due to the [classic 'self or associated type' error](https://www.natashatherobot.com/swift-type-erasure/). Code such as this is generated:

```
class MockMyProtocol: MyProtocol, Cuckoo.ProtocolMock {
    typealias MocksType = MockMyProtocol
    private var __defaultImplStub: MockMyProtocol? // <-- this line won't compile, for example
```

Note: I'm generating with something along the lines of:
```./Pods/Cuckoo/run generate --output tmp.swift --no-class-mocking --no-timestamp Path/To/MyProtocol.swift
```

As you can see in the solution section of the blog post above - you need to write/generate a concrete struct - `AnyMyProtocol<T>` in this case.

I'd be happy to in some way mark my protocol with all the information Cuckoo needs to generate working code - (what the boxing type is, what the generics are, even what I'd like them erased to).

Could Cuckoo support this mode of operation?

**Comment by MatyasKriz** [comment]
Merged!
