### ISSUE TITLE
The word "import" in a top-level comment of a source file is interpreted as an import statement by Cuckoo

### ISSUE THREAD

**Issue by msewell** [Brightify/Cuckoo#208]
(Observed in Cuckoo 0.11.3.)

Using the word "import" in e. g. the documentation comment for a mock source leads to a compile error in the generated Mock file, as Cuckoo interprets it as an import statement.

Example source file (`ImportedWine.swift`):
```swift
/// Tracks the import of fine wines.
public protocol ImportedWine {
    var exportingCountry: String { get }
    var importingCountry: String { get }
}
```

Generated mock file (`MockImportedWine.swift`) (excerpt):
```swift
...
/// Tracks the 
import Cuckoo

import of // 💥 Compile error: "No such module 'of'"

class MockImportedWine: ImportedWine, Cuckoo.ProtocolMock {
...
```

**Comment by MatyasKriz** [comment]
Hey, I tried to reproduce this in the current version (`1.0.5`) without any luck. If you, or anyone else with this issue, added a test class to the cuckoo project that brings this behavior out of the generator, I'd be happy to fix it.

Until this problem manifests again with an easily reproducible code, I'll close this issue. Don't hesitate to reopen it if you've got the test case done.
