### ISSUE TITLE
Support Modules Whose Name Differs from Project

### ISSUE THREAD

**Issue by mylesbarros** [Brightify/Cuckoo#209]
I'm attempting to use Cuckoo in a project called "CoolFooApp". The testing target that runs Cuckoo tests against a module called "Cool Foo". As a result, Cuckoo generates a mock file that starts with `@testable import CoolFooApp` and fails the build.

It would be nice to configure this as an argument to the `run` command line tool.

**Comment by MatyasKriz** [comment]
Hey there!
Setting testable imports is actually as easy as 1, 2, 3.
According to the `README.md`, the generator parameter `--testable` serves this very purpose:
> A comma separated list of frameworks that should be imported as @testable in the mock files.

So in your generation script, simply change `--testable "$PROJECT_NAME"` -> `--testable "Cool_Foo"` or even `--testable "Cool Foo"` (contains a space) if you're brave enough. The generator will convert it into `Cool_Foo` for you.

Unfortunately this needs to be hardcoded as there are no enviroment variables that would help us get the "main" module name. The closest is `$PRODUCT_MODULE_NAME`, but considering you're probably running it in tests module of its own, it's no good.

More enviroment variables if you're curious: https://help.apple.com/xcode/mac/8.0/#/itcaec37c2a6

Hope this answers all the follow-up questions. If not, just let me know! I know we'll get there eventually.
