### ISSUE TITLE
Support Compiler Directives

### ISSUE THREAD

**Issue by adamdebono** [Brightify/Cuckoo#213]
I have a project which shares a bunch of code between iOS and tvOS, and I have used a number of compiler directives in my code to handle some of the differences between them.

For Example, tvOS doesn't support the `LocalAuthentication` framework, so I have put a directive around a few things so that it only applies on iOS:
```swift
class UserManager {
    #if os(iOS)
    private let authenticationContext: LAContext = {
        let context = LAContext()
        context.localizedCancelTitle = "Enter Manually"
        return context
    }()
    #endif
}
```

Cuckoo seems to ignore these directives completely, and so if I were to run the Cuckoo generator on the above code, it would include the `authenticationContext` variable in the mocks no matter what. 

When compiling my tests for tvOS I get a bunch of compiler errors including:
- Property does not override any property from its superclass
- Method does not override any property from its superclass
- Value of type 'NameOfClass' has no member 'nameOfProperty'
- Use of undeclared type 'NameOfClass'

**Comment by MatyasKriz** [comment]
Hey there!
As of now, while using SourceKitten, we are unable to see compiler directives.
Running this command:
```
sourcekitten structure --text "
protocol Protocol {
#if os(iOS)
    func M()
#endif
}"
```
->
```
{
  "key.diagnostic_stage" : "source.diagnostic.stage.swift.parse",
  "key.length" : 54,
  "key.offset" : 0,
  "key.substructure" : [
    {
      "key.accessibility" : "source.lang.swift.accessibility.internal",
      "key.bodylength" : 33,
      "key.bodyoffset" : 20,
      "key.kind" : "source.lang.swift.decl.protocol",
      "key.length" : 53,
      "key.name" : "Protocol",
      "key.namelength" : 8,
      "key.nameoffset" : 10,
      "key.offset" : 1,
      "key.runtime_name" : "_TtP4main8Protocol_",
      "key.substructure" : [
        {
          "key.accessibility" : "source.lang.swift.accessibility.internal",
          "key.kind" : "source.lang.swift.decl.function.method.instance",
          "key.length" : 8,
          "key.name" : "M()",
          "key.namelength" : 3,
          "key.nameoffset" : 42,
          "key.offset" : 37
        }
      ]
    }
  ]
}
```
There is nothing that would tell us of the compiler directive and if we parsed the file ourselves, there would be no use of an external parser. Creating a parser for Cuckoo would not be that time-consuming, but it would have to be maintained throughout the Swift versions. For that we don't have enough manpower right now.
Thank you for understanding! When it comes to creating/adopting a new parser, we'll try to make sure it supports compiler directives.

**Comment by paul-rolfe-rivian** [comment]
Is there a workaround for this? @MatyasKriz ?

**Comment by MatyasKriz** [comment]
Hi! There's unfortunately no workaround at this time. I know this feature would be very nice to have, but it hasn't been implemented yet and I'm currently pretty bogged down to use SwiftFormat for generating code which would make adding this much easier.

You can track the current issue here: https://github.com/Brightify/Cuckoo/issues/471

**Comment by paul-rolfe-rivian** [comment]
Ok, thanks for working on it. @MatyasKriz 

For anyone else trying to overcome this. I figured out you can use `sed` after the code generation in your build script to remove any unwanted code. For example:

```
"${PODS_ROOT}/Cuckoo/run"

# Cuckoo can't handle compiler directives, so we have to manually remove some stuff
sed -i '' -E '/^import .+_Watch$/d' ${SCRIPT_OUTPUT_FILE_0}
```
