### ISSUE TITLE
Can not generate GeneratedMocks.swift file

### ISSUE THREAD

**Issue by kamashany** [Brightify/Cuckoo#217]
I followed up the docs but unfortunately nothing helped me.

**Comment by kamashany** [comment]
This is the script:

# Define output file; change "${PROJECT_NAME}Tests" to your test's root source folder, if it's not the default name
OUTPUT_FILE="./${PROJECT_NAME}Tests/GeneratedMocks.swift"
echo "Generated Mocks File = ${OUTPUT_FILE}"

# Define input directory; change "${PROJECT_NAME}" to your project's root source folder, if it's not the default name
INPUT_DIR="./${PROJECT_NAME}"
echo "Mocks Input Directory = ${INPUT_DIR}"

# Generate mock files; include as many input files as you'd like to create mocks for
${PODS_ROOT}/Cuckoo/run generate --testable "${PROJECT_NAME}"
--output "${OUTPUT_FILE}"
"${INPUT_DIR}/UrlSession.swift"

**Comment by TadeasKriz** [comment]
Hi, it seems you're missing `\` at the end of line `${PODS_ROOT}/Cuckoo/run generate --testable "${PROJECT_NAME}"` and `--output "${OUTPUT_FILE}"`

**Comment by kamashany** [comment]
I did it but Unfortunately It's not working as well.

**Comment by TadeasKriz** [comment]
Please show us the error you're getting and the new script.

**Comment by kamashany** [comment]
No errors. I just compile the project to generate the mocks file but nothing generated.

**Comment by TadeasKriz** [comment]
Then show me the log from the "Generate" run script phase.

**Comment by kamashany** [comment]
It's just a demo project to find out how this library is working.

**Comment by kamashany** [comment]
[UrlWithCuckoo.zip](https://github.com/Brightify/Cuckoo/files/2283052/UrlWithCuckoo.zip)

Please have a look at it. It's just one file "UrlSession" which want to mock.

**Comment by kamashany** [comment]
I did the two things as you told but not working too.

**Comment by TadeasKriz** [comment]
What does "not working" mean exactly? I got the `GeneratedMocks.swift` file generated by running tests on the project you've sent me.

**Comment by kamashany** [comment]
How did you run tests ?

**Comment by TadeasKriz** [comment]
`Cmd+U`

**Comment by kamashany** [comment]
There is one error when running it.

Generated Mocks File = ./UrlWithCuckooTests/GeneratedMocks.swift
Mocks Input Directory = ./UrlWithCuckoo
/Users/mikamashany/Library/Developer/Xcode/DerivedData/UrlWithCuckoo-gchjdxnsscylatawmwfcvjlqvqnq/Build/Intermediates.noindex/UrlWithCuckoo.build/Debug-iphonesimulator/UrlWithCuckooTests.build/Script-983441832121B30D00E3238F.sh: line 11: /Users/mikamashany/Desktop/iOS/useful: No such file or directory

**Comment by TadeasKriz** [comment]
You have a space in the path to project. Change the script to:

```
# Define output file; change "${PROJECT_NAME}Tests" to your test's root source folder, if it's not the default name
OUTPUT_FILE="./${PROJECT_NAME}Tests/GeneratedMocks.swift"
echo "Generated Mocks File = ${OUTPUT_FILE}"

# Define input directory; change "${PROJECT_NAME}" to your project's root source folder, if it's not the default name
INPUT_DIR="./${PROJECT_NAME}"
echo "Mocks Input Directory = ${INPUT_DIR}"

# Generate mock files; include as many input files as you'd like to create mocks for
"${PODS_ROOT}/Cuckoo/run generate" --testable "${PROJECT_NAME}"
--output "${OUTPUT_FILE}"
"${INPUT_DIR}/UrlSession.swift"
```

**Comment by kamashany** [comment]
where is the backslash ?

**Comment by TadeasKriz** [comment]
You're right, I copied your old script, my bad.

**Comment by TadeasKriz** [comment]
Updated it.

**Comment by kamashany** [comment]
The same error

Generated Mocks File = ./UrlWithCuckooTests/GeneratedMocks.swift
Mocks Input Directory = ./UrlWithCuckoo
/Users/mikamashany/Library/Developer/Xcode/DerivedData/UrlWithCuckoo-gchjdxnsscylatawmwfcvjlqvqnq/Build/Intermediates.noindex/UrlWithCuckoo.build/Debug-iphonesimulator/UrlWithCuckooTests.build/Script-983441832121B30D00E3238F.sh: line 11: /Users/mikamashany/Desktop/iOS/useful Demos/UrlWithCuckoo/Pods/Cuckoo/run generate: No such file or directory

**Comment by TadeasKriz** [comment]
Take a look inside the `Pods/Cuckoo` if the `run` is there.

**Comment by kamashany** [comment]
Yes it's there.

**Comment by kamashany** [comment]
For your information i renamed the directory name to delete the white space but the error is still there

**Comment by TadeasKriz** [comment]
I updated the script, I enclosed the "generate" in the quotes as well which was wrong.

**Comment by kamashany** [comment]
The error is still there.

**Comment by TadeasKriz** [comment]
Show me the script now.

**Comment by kamashany** [comment]
# Define output file; change "${PROJECT_NAME}Tests" to your test's root source folder, if it's not the default name
OUTPUT_FILE="./${PROJECT_NAME}Tests/GeneratedMocks.swift"
echo "Generated Mocks File = ${OUTPUT_FILE}"

# Define input directory; change "${PROJECT_NAME}" to your project's root source folder, if it's not the default name
INPUT_DIR="./${PROJECT_NAME}"
echo "Mocks Input Directory = ${INPUT_DIR}"

# Generate mock files; include as many input files as you'd like to create mocks for
"${PODS_ROOT}/Cuckoo/run generate" --testable "${PROJECT_NAME}" \
--output "${OUTPUT_FILE}" \
"${INPUT_DIR}/UrlSession.swift"

**Comment by TadeasKriz** [comment]
You didn't copy paste the updated one

**Comment by TadeasKriz** [comment]
Here's it again just for sure:

```
# Define output file; change "${PROJECT_NAME}Tests" to your test's root source folder, if it's not the default name
OUTPUT_FILE="./${PROJECT_NAME}Tests/GeneratedMocks.swift"
echo "Generated Mocks File = ${OUTPUT_FILE}"

# Define input directory; change "${PROJECT_NAME}" to your project's root source folder, if it's not the default name
INPUT_DIR="./${PROJECT_NAME}"
echo "Mocks Input Directory = ${INPUT_DIR}"

# Generate mock files; include as many input files as you'd like to create mocks for
"${PODS_ROOT}/Cuckoo/run" generate --testable "${PROJECT_NAME}" \
--output "${OUTPUT_FILE}" \
"${INPUT_DIR}/UrlSession.swift"
```

**Comment by kamashany** [comment]
Now it's being generated. Many Thanks to you 👍

**Comment by TadeasKriz** [comment]
👍
