### ISSUE TITLE
Type 'MyDataManager' does not conform to protocol 'Mock'

### ISSUE THREAD

**Issue by arkilis** [Brightify/Cuckoo#223]
After generate the GeneratedMocks.swift, the whole unit test cannot be run any more, and all errors happened in GeneratedMocks.swift. 

Errors:

![image](https://user-images.githubusercontent.com/1528028/46182260-0e334680-c30e-11e8-86b5-8a1fe6c8af32.png)

**Comment by MatyasKriz** [comment]
Do you think you could provide us with the `GeneratedMocks.swift` file? It would be a great help into seeing why you're having these errors.

**Comment by MatyasKriz** [comment]
Hey, we can't figure it out without any leads, I'm closing this issue for now until you provide `GeneratedMocks.swift`.
