### ISSUE TITLE
Cuckoo appears to try to look into framework directories of dependancies.

### ISSUE THREAD

**Issue by aramark-pivotal** [Brightify/Cuckoo#226]
We are invoking cuckoo to build our mocks like:
- Define output file. Change $PROJECT_DIR/Tests to your test's root source folder, if it's not the default name.
OUTPUT_FILE="$PROJECT_DIR/PattyMeltTests/GeneratedMocks.swift"
echo Generated Mocks File = $OUTPUT_FILE

- Define input directory. Change $PROJECT_DIR to your project's root source folder, if it's not the default name.
INPUT_DIR=$PROJECT_DIR
echo Mocks Input Directory = $INPUT_DIR

mockFiles() {
    echo $(find ${INPUT_DIR}/MyApp/PresentationLayer -name '*.swift' && find ${INPUT_DIR}/MyApp/DataLayer -name '*.swift' && find ${INPUT_DIR}/MyApp/BusinessLayer -name '*.swift' && find ${INPUT_DIR}/MyApp/SystemLayer -name '*.swift')
}

echo $(mockFiles)

- Generate mock files, include as many input files as you'd like to create mocks for.
${PODS_ROOT}/Cuckoo/run generate --testable "$PROJECT_NAME" \
--output ${OUTPUT_FILE} $(mockFiles)

- After running once, locate GeneratedMocks.swift and drag it into your Xcode test target group.

And here is a partial log output:
Could not read contents of `/Users/porter-jerry/Developer/Source/workarea/patty-melt-ios/Carthage/Build/iOS/CryptoSwift.framework`
Could not read contents of `/Users/porter-jerry/Developer/Source/workarea/patty-melt-ios/Carthage/Build/iOS/Nimble.framework`
Could not read contents of `/Users/porter-jerry/Developer/Source/workarea/patty-melt-ios/Carthage/Build/iOS/ObjcExceptionBridging.framework`
Could not read contents of `/Users/porter-jerry/Developer/Source/workarea/patty-melt-ios/Carthage/Build/iOS/Quick.framework`
Could not read contents of `/Users/porter-jerry/Developer/Source/workarea/patty-melt-ios/Carthage/Build/iOS/RxBlocking.framework`
Could not read contents of `/Users/porter-jerry/Developer/Source/workarea/patty-melt-ios/Carthage/Build/iOS/RxTest.framework`
Could not read contents of `/Users/porter-jerry/Developer/Source/workarea/patty-melt-ios/Carthage/Build/iOS/XCGLogger.framework`

**Comment by MatyasKriz** [comment]
I was unable to find out why would Cuckoo do this when it uses only the paths that are provided to it. If this problem is still relevant, we can reopen and discuss it further.
