### ISSUE TITLE
XCode 10 Build input file cannot be found: '.....Tests/Mocks/GeneratedMocks.swift'

### ISSUE THREAD

**Issue by andyryan** [Brightify/Cuckoo#228]
I have recently updated to Xcode 10 and i receive this warning when i try and run a fresh clone on our project (and is therefor a problem for our continuous integration system). After the failed build it works fine and the file is present. I suspect there is some race condition between the file being created, and the next step checking for its presence.

**Comment by andyryan** [comment]
I seem to have found a solution myself:

This is occurring due to new parallelisation of the build process so yes, the "compile sources" step which required GeneratedMocks.swift was firing before the Run Script step for cuckoo had finished.

To get around this, you need to add the output file to the "Output Files" section below the script. You can copy+paste whatever you have for your `OUTPUT_FILE` param

My impression is that this tells Xcode to wait for the file to have ben created before proceeding.

**Comment by phillippbertram** [comment]
I still came across this problem today and the hint from @andyryan solved this problem 👍 
Perhaps it would make sense to update the README accordingly? 🙃

**Comment by MatyasKriz** [comment]
Hey, @phillippbertram makes sense. Quite a lot of likes as well. Will add it as soon as my schedule allows it. Thanks for pointing this out.
