### ISSUE TITLE
<@available> attribute

### ISSUE THREAD

**Issue by LeonKarabchevsky** [Brightify/Cuckoo#231]
I have a class which I would like to mock, the class is assigned with the following attribute @available(iOS 10.0, *).
The issue I see, is that GeneratedMocks.swift file does not assign the attribute to the generated mocks, resulting in an error '<class> us only available on IOS 10.0 or newer'.

**Comment by MatyasKriz** [comment]
Hi,
I'm sorry in advance if I got your hopes up. I didn't realize that SourceKit doesn't give us enough info to implement this.
Looking at the output of the command
```bash
sourcekitten structure --text "@available(swift 3.0.3) class C { }"
```
->
```bash
{
  "key.diagnostic_stage" : "source.diagnostic.stage.swift.parse",
  "key.length" : 35,
  "key.offset" : 0,
  "key.substructure" : [
    {
      "key.accessibility" : "source.lang.swift.accessibility.internal",
      "key.attributes" : [
        {
          "key.attribute" : "source.decl.attribute.available",
          "key.length" : 23,
          "key.offset" : 0
        }
      ],
      "key.bodylength" : 1,
      "key.bodyoffset" : 33,
      "key.kind" : "source.lang.swift.decl.class",
      "key.length" : 11,
      "key.name" : "C",
      "key.namelength" : 1,
      "key.nameoffset" : 30,
      "key.offset" : 24,
      "key.runtime_name" : "_TtC4main1C"
    }
  ]
}
```
It would require us to parse the file by ourselves using the markers provided by SourceKit (which would defeat the purpose of using an external parser). It's on our TODO list, but it hasn't the highest priority right now. Sorry.

Thanks for creating the issue, we'll be more inclined to make sure the next parser has the capability to parse these attributes.

**Comment by MatyasKriz** [comment]
Actually I spoke too soon. As our team lead pointed out, the SourceKit is telling us where to find the attribute and we just copy the text over to the generated file. Should be up in the next version. Thanks for your patience!

**Comment by gfk-sensic** [comment]
It's still not available in the current version, right?

**Comment by MatyasKriz** [comment]
I'm not sure, but a PR has been submitted and the issue closed, so try it out and let me know.

**Comment by gfk-sensic** [comment]
I tried and its not working..

**Comment by MatyasKriz** [comment]
That's a pretty vague description. Could you please clear it up a bit?

What code snippet are you trying to mock?

Is it not generating or is the generated code uncompilable?

What Xcode and Cuckoo versions are you using?

**Comment by gfk-sensic** [comment]
So I have a class which is annotated with the following attribute @available(iOS 11.0, *). The Mock class which is generated does not have this annotation. So I am not able to start my tests because of a compiling error.
XCode version: 11.5
Cuckoo version: latest

**Comment by MatyasKriz** [comment]
Maybe I added the support for methods only, not sure, it's been a while. I'll take a look at it as soon as I have some time.

**Comment by gfk-sensic** [comment]
Okay.. Thanks! But initially the question from 2018 was also about a class... Just to let you know...

**Comment by MatyasKriz** [comment]
So I checked it out in the codebase, we actually do have tests for this and they pass (the property and class both have the correct `@available` attribute).

Please fork Cuckoo and add a minimal reproducible example into the tests that fails to copy the attribute over to the generated code.
