### ISSUE TITLE
Prevent mocking of final class.

### ISSUE THREAD

**Issue by petaren** [Brightify/Cuckoo#242]
If I have a class defined as `final class Foo {}`, Cuckoo will create a mock for it as such: `class MockFoo: Foo`. This causes the swift-compiler to complain about it attempting to subclass a final class. 

I think Cuckoo should skip classes defined as `final`.

**Comment by MatyasKriz** [comment]
Hey, thanks for creating the issue. I'll implement skipping over `final` classes, should be out in the next release.

**Comment by MatyasKriz** [comment]
PR is up! Let's be hopeful for some quick reviewing and then it'll be live.

**Comment by MatyasKriz** [comment]
Merged!
