### ISSUE TITLE
Verify multiple method calls with different parameters

### ISSUE THREAD

**Issue by zcsipler** [Brightify/Cuckoo#247]
If the same method is called in a test case, we use times(2) in verify to tell Cuckoo that this method should be called twice. But what happens if the same method is called two times but with a different parameter value per call? Is there any way to separately verify parameter for the first call and the second call?

**Comment by zcsipler** [comment]
I discovered that ArgumentCaptor solves this.

**Comment by MatyasKriz** [comment]
Cool! If you have a second, could you please elaborate a bit further for those that might find themselves in your situation? 🙂 
Thanks!

**Comment by zcsipler** [comment]
@MatyasKriz so the example something like this:

Original code: 

```
interactor.helloWorld(helloWorldString: "HelloWorld1")
interactor.helloWorld(helloWorldString: "HelloWorld2")
```

Test:

```
let argumentCaptor = ArgumentCaptor<String>()

                    verify(mockInteractor, times(2)).helloWorld(helloWorldString: argumentCaptor.capture())

                    expect(argumentCaptor.allValues[safe: 0]).to(equal("HelloWorld1")) // Verify parameter for the first call
                    expect(argumentCaptor.allValues[safe: 1]).to(equal("HelloWorld2")) // Verify parameter for the second call
```

@TadeasKriz I am not sure what you mean exactly but my point was to verify parameters for multiple calls and I think the example above does exactly what I wanted :)

**Comment by TadeasKriz** [comment]
Try:

```
verify(mockInteractor, times(1)).helloWorld(helloWorldString: "HelloWorld1")
verify(mockInteractor, times(1)).helloWorld(helloWorldString: "HelloWorld2")
```

Should work exactly as you need.

**Comment by zcsipler** [comment]
@TadeasKriz  You are right, this works as well. However if we wanted to verify non matchable parameters we would need to use ParameterMatcher but we  prefer to use nimble's expect for parameter verification instead of putting if-else statements into parametermatcher block. Also ArgumentCaptor is more accurate since we can check the order of the calls (e.g. the first call we expect HelloWorld1, the 2nd call we expect HelloWorld2 parameter).
