### ISSUE TITLE
Ignore method calls in init

### ISSUE THREAD

**Issue by vladr11** [Brightify/Cuckoo#252]
Is it possible to ignore the calls methods when called from `init`? The main use case is when an initialize routine is inherited and therefore cannot be declared `private` to be ignored by the mock generator. When creating the mocks there is no way to stub these methods before them being called.

**Comment by TadeasKriz** [comment]
Hi, with the new initialisation, you should be able to get around this. Try something like:

```
let mock = createMock(for: SomeClass.self) { builder, stub in
    when(stub.readOnlyProperty.get).thenReturn("a")

    return MockSomeClass()
}
```

This way you are able to stub before init is called. I'm not sure if we have the functionality to ignore just yet, you can take a look at the methods of the `builder` parameter you get into the closure.

**Comment by MatyasKriz** [comment]
Assuming that this issue is now resolved, I'm closing it.

**Comment by vladr11** [comment]
Yes, the issue is solved. Thank you.
