### ISSUE TITLE
Multiple mock generation build db contention

### ISSUE THREAD

**Issue by aramark-pivotal** [Brightify/Cuckoo#254]
We have been using Cuckoo via Pods in our project for quite some time. (Xcode 9.3.1, fastlane and CircleCI)

However, as our project has grown, the time to generate mocks takes about 15 minutes per cycle.
We decided to try and break mock generation into four targets and added them as dependencies to out UnitTests target.
This worked out quite well as we are now able to parallelize mock generation to about 5 minutes a cycle.

We then upgraded to Xcode 10.1 and Carthage for Cuckoo.
We then had issues with mock generation on CircleCI.
Xcode and xcodbuild worked just fine.

The stem of the problem is the 'run' script was having trouble detecting the cuckoo_generator when using a Carthage install in CI. 
The issue appears that when multiple mocks are generated, the 'run' script attempts to build the cuckoo_generator multiple times and there is a build DB contention.
It doesn't see that the generator is fetched and ready to go, so, naturally it fetches the building tools to 'generate' cuckoo_generator.

When you have your mocks split up this means it will attempt to generate multiple cuckoo_generator's at once.
Actually, all four of our build targets ended up pointing to the same directory rebuilding the same code four times.
When this happens, the internal source database to locks up, the cuckoo_generator generation fails, and ultimately no cuckoo_generator is created.

We were able to salvage this by pre-generating the cuckoo_generator and bundling it in our repository.
We then removed the call to the run script and call the cuckoo_generator directly. 
When multiple cuckoo_generator's generate mocks at the same time there is no db lock so it works normally.

Is this an issue that can be addressed?

**Comment by MatyasKriz** [comment]
Hey, I know we were discussing this issue on Slack, were you able to mitigate this issue by downloading the `cuckoo_generator` instead of building it?

**Comment by BrooksDuBoisAramark** [comment]
yes we eventually we're able to resolve our issues by generating the cuckoo generator, writing a bit of our own implementation in bash, then reference the `cuckoo_generator` executable.

**Comment by MatyasKriz** [comment]
Alright, thanks for the info. 🙂 

It seems you found a pretty good way of going around it. You'd probably be able to shorten the "build" time even further by downloading the `cuckoo_generator` from GitHub by passing the `--download [VERSION]` (blank for latest) parameter to the `run` script.
