### ISSUE TITLE
Not able to stub a protocol method, however there is generated mocked code for the method.

### ISSUE THREAD

**Issue by wavesinclined** [Brightify/Cuckoo#256]
This is the error log while stubbing and testing the Mocked Protocol.
```
No stub for method getWithdrawals(name: String, startDate: Date, endDate: Date) -> Observable<FetchEvent<[Withdrawal]>> using parameters ("", 2019-01-23 18:30:00 +0000, 2019-02-22 18:29:59 +0000).
```

This is the autogenerated mocked method.

```
func getWithdrawals<M1: Cuckoo.Matchable, M2: Cuckoo.Matchable, M3: Cuckoo.Matchable>(name: M1, startDate: M2, endDate: M3) -> Cuckoo.ProtocolStubFunction<(String, Date, Date), Observable<FetchEvent<[Withdrawal]>>> where M1.MatchedType == String, M2.MatchedType == Date, M3.MatchedType == Date {
  let matchers: [Cuckoo.ParameterMatcher<(String, Date, Date)>] = [wrap(matchable: name) { $0.0 }, wrap(matchable: startDate) { $0.1 }, wrap(matchable: endDate) { $0.2 }]
  return .init(stub: cuckoo_manager.createStub(for: MockCachedRepository.self, method: "getWithdrawals(name: String, startDate: Date, endDate: Date) -> Observable<FetchEvent<[Withdrawal]>>", parameterMatchers: matchers))
}
```

I cannot stub the protocol (Cached Repository) method for testing.

**Comment by wavesinclined** [comment]
This is the error log while stubbing and testing the Mocked Protocol.
No stub for method `getWithdrawals(name: String, startDate: Date, endDate: Date) -> Observable<FetchEvent<[Withdrawal]>>` using parameters ("", 2019-01-23 18:30:00 +0000, 2019-02-22 18:29:59 +0000).

This is the autogenerated mocked method.

 func getWithdrawals<M1: Cuckoo.Matchable, M2: Cuckoo.Matchable, M3: Cuckoo.Matchable>(name: M1, startDate: M2, endDate: M3) -> Cuckoo.ProtocolStubFunction<(String, Date, Date), Observable<FetchEvent<[Withdrawal]>>> where M1.MatchedType == String, M2.MatchedType == Date, M3.MatchedType == Date {
	        let matchers: [Cuckoo.ParameterMatcher<(String, Date, Date)>] = [wrap(matchable: name) { $0.0 }, wrap(matchable: startDate) { $0.1 }, wrap(matchable: endDate) { $0.2 }]
	        return .init(stub: cuckoo_manager.createStub(for: MockCachedRepository.self, method: "getWithdrawals(name: String, startDate: Date, endDate: Date) -> Observable<FetchEvent<[Withdrawal]>>", parameterMatchers: matchers))
	   }
I cannot stub the protocol (Cached Repository) method for testing.

**Comment by MatyasKriz** [comment]
Hey, I just had to reformat your comment to use the markdown code ticks because I couldn't navigate through it in plain text.

Could you please give us a way to test this by providing the test case where you're calling the mocked method?

**Comment by aramark-pivotal** [comment]
Any function that is called inside of mock, even if it is indirectly chained, will need stub data or you will get this error.  You have to actually stub that mock with data.

Another option is to define defaults for all the return types for that object and enable defaults with the Stub class.

**Comment by MatyasKriz** [comment]
Thanks to @aramark-pivotal for the explanation, this seems to be a problem of not providing a stub yourself and calling the method without enabling default implementation.

@wavesinclined, feel free to comment for further info about your problem, however, I'll be closing this issue.
