### ISSUE TITLE
Compilation error for "inout" arguments

### ISSUE THREAD

**Issue by ealymbaev** [Brightify/Cuckoo#260]
Hey, I am using GRDB library for storing my models in database. And also I want to mock those models using Cuckoo.

The issue is that GRDB requires me to override the following function:

```
open func encode(to container: inout PersistenceContainer) {}
```

Cuckoo, on the other hand, tries to mock it and gives me compilation error in GeneratedMocks file. I guess it simply cannot handle `inout` yet.

Moreover, I cannot even exclude this function from mocking, because I don't really need mock for this function.

I also tried to mark this overridden function as `final` but Cuckoo still cannot handle this correctly.

**Comment by MatyasKriz** [comment]
Hey! Thanks for the report. I didn't even realize that `final` classes are a thing, so naturally I forgot to include them in ignoring `final` code structures.

As for `inout` parameters, support for those has been added as well.

Both the `final` fix and `inout` support will be in the next release. If you'd like to continue without delay on your project, you can use the branch `inout-types` which also has the `final` fix included.

**Comment by ant013** [comment]
Hey! I tried use inout-types branch, but still has same troubles. GeneratedMocks still add inout for properties when create func

**Comment by MatyasKriz** [comment]
Merged! I do not understand what you're trying to say, but if you formulate it better, we can address it in future releases.
