### ISSUE TITLE
Optional parameters in functions not supported?

### ISSUE THREAD

**Issue by pffan91** [Brightify/Cuckoo#263]
I have two functions:

```
// 1
internal func isAuraDevice(deviceName: String?) -> Bool

// 2
public func isHasService(serviceUUID: String) -> Promise<Void>
```

The second one I can use like this `when(stub.isHasService(serviceUUID: "AAAA-AAAA")).thenReturn(Promise())`. When I am using the first one `when(stub.isMyDevice(deviceName: "Apple Watch 4")).thenReturn(false)` it does not compile with error: "Generic parameter 'M1' could not be inferred". Why this happens?

**Comment by MatyasKriz** [comment]
Hey! Optional parameters are supported, it's just a tad tricky to get right so that you can call stubbing and verifying with the nonoptional values, like you're trying to do.

At the moment, you can just call:
```
when(stub.isAuraService(deviceName: Optional("Apple Watch 4"))).thenReturn(false)
// or
when(stub.isAuraService(deviceName: equal(to: "Apple Watch 4"))).thenReturn(false)
```
