### ISSUE TITLE
No such module 'Cuckoo' in GeneratedMocks.swift

### ISSUE THREAD

**Issue by closer27** [Brightify/Cuckoo#267]
Hi, I have a problem with building the test target.

I followed your guide for generating mock classes, and I checked that GeneratedMocks.swift was created well.
And then I added it to the test target in my project workspace, but I can see an error `no such module Cuckoo` at`import Cuckoo` on the first line.

I tried `pod deintegrate; pod install` and cleaned my project, remove derived files, but It didn't help. 
Please let me know If I omit something. Thank you

**Comment by MatyasKriz** [comment]
Please make sure that you've added `Cuckoo` to your test target in the `Podfile`.

**Comment by MatyasKriz** [comment]
Hey, did that do it? Another possibility is that you have the `GeneratedMocks.swift` file targetted to your production target. You can set it to your test target using the right pane in Xcode while having the file open.

**Comment by MatyasKriz** [comment]
I'll close this issue for now. Feel free to reopen it in case neither of the possible fixes helped your situation.

**Comment by bupojung** [comment]
Have the same error. I have add Cuckoo to my test target like this

target 'XXDemo' do
  appPods
  sdkPods
  target 'XXDemoTests' do
    inherit! :search_paths
    pod "Cuckoo", '1.6.0'
  end
end
