### ISSUE TITLE
Prefix types with the module they come from

### ISSUE THREAD

**Issue by CraigSiemens** [Brightify/Cuckoo#283]
In my project, I'm defining protocols to use for dependency injection. When used for injecting system provided classes, I'm purposefully calling my protocol the same as the type from Foundation to discourage bypassing our dependency injection. An example if this would be

```swift
protocol FileManager {
    //methods
}

extension Foundation.FileManager: FileManager { }
```

The issue come from the generated file.

```swift
class MockFileManager: FileManager, Cuckoo.ProtocolMock {
```

It creates the following error
```
GeneratedMocks.swift:19:28: 'FileManager' is ambiguous for type lookup in this context
```

This makes sense, the compiler doesn't know whether to use `Foundation.FileManager` or `MyApp.FileManager`. It would be nice if there was an option for the generated code to prefix the types with the module name. An example of that would be

```swift
class MockFileManager: MyApp.FileManager, Cuckoo.ProtocolMock {
```

**Comment by MatyasKriz** [comment]
Hey, we are aware of this necessity from some users of Cuckoo as discussed in the previous issue about third party modules as well as ambiguous class and protocol names – #224.

It's likely a superset of the feature you're requesting where you only want to use the app's classes and protocols that collide with Foundation's names.

I'm not aware of a way to do this automatically, so in #224 I proposed a configuration file where you would define these modules and files from the modules would get automatically prefixed with the defined module name.

It's not, however, by any means a small feature and I can't say when it could be ready at the moment.

Please move further discussion to #224 to not diversify the discussions as they are one and the same.
