### ISSUE TITLE
cuckoo_generator download path vs run path

### ISSUE THREAD

**Issue by jamezilla** [Brightify/Cuckoo#285]
There's a disconnect between the notion of the `cuckoo_generator` download path and it's run path in the `run` script. The download path is just the file name, so if the script is invoked from outside the Cuckoo directory, the script is downloaded there. The subsequent call to run the generator fails because it's using the absolute path to the Cuckoo directory. 

[Line 15](https://github.com/Brightify/Cuckoo/blob/master/run#L15): 
```
  curl "${CURL_OPTIONS[@]}" -Lo "$FILE_NAME" "$DOWNLOAD_URL"
```
...should probably be changed to:
```
  curl "${CURL_OPTIONS[@]}" -Lo "$FILE_PATH" "$DOWNLOAD_URL"
```
...to match the [generator invocation](https://github.com/Brightify/Cuckoo/blob/master/run#L106):
```
echo $INPUT_FILES | xargs "$FILE_PATH"
```

**Comment by MatyasKriz** [comment]
Nice catch, @jamezilla. Will you submit a PR that fixes this undesired behavior?
