### ISSUE TITLE
How to create custom matcher for enum argument type in method?

### ISSUE THREAD

**Issue by JIVIJA** [Brightify/Cuckoo#289]
I have tried to create custom matcher. But getting following error. 

![Screenshot 2019-05-27 at 4 09 02 PM](https://user-images.githubusercontent.com/16122807/58414970-a1d63600-809a-11e9-9f3a-7255f3cdab3e.png)

**Comment by MatyasKriz** [comment]
Hey, I'd like to help you, but I need to know the code to `RegistrationTrackerModel.Event`.

I tried it like this and it worked for me on `1.0.5`:
```
enum Enumeracion: Equatable {
    case dude(String)
    case duda(Int)
}

...

let matcher = ParameterMatcher<Enumeracion> { enumio in
    enumio == Enumeracion.dude("jaja")
}
```

**Comment by TadeasKriz** [comment]
@MatyasKriz Doesn't `Equatable` give you the possibility to just `equal(to: .dude("jaja"))`?

**Comment by MatyasKriz** [comment]
@TadeasKriz It sure does. I think that's what's missing in @JIVIJA's `enum`.

**Comment by TadeasKriz** [comment]
@JIVIJA If you can't make the `enum` conform to `Equatable`, you could write the matcher like so:

```
let matcher = ParameterMatcher<RegistrationTrackerModel.Event> { tested in 
    if case .userRegistration("some userId") = tested {
        return true
    } else { 
        return false
    }
}
```

**Comment by JIVIJA** [comment]
> @JIVIJA If you can't make the `enum` conform to `Equatable`, you could write the matcher like so:
> 
> ```
> let matcher = ParameterMatcher<RegistrationTrackerModel.Event> { tested in 
>     if case .userRegistration("some userId") = tested {
>         return true
>     } else { 
>         return false
>     }
> }
> ```

it works.
