### ISSUE TITLE
Property cannot be declared public because its type uses an internal type

### ISSUE THREAD

**Issue by andyryan** [Brightify/Cuckoo#292]
Since updating to the latest version, I am getting build errors in GeneratedMocks due to type accessibility that wasn't an issue before.

For example

I have the following public class 
```
public class client {
    internal var delegates: [ClientDelegate]
}

class [ClientDelegate] {

}
```
However, cuckoo is trying to make the `delegates` var public:
```
public override var delegates: [ClientDelegate] {
        get {
            return cuckoo_manager.getter("delegates",
                superclassCall:
                    
                    super.delegates
                    ,
                defaultCall: __defaultImplStub!.delegates)
        }
        
        set {
            cuckoo_manager.setter("delegates",
                value: newValue,
                superclassCall:
                    
                    super.delegates = newValue
                    ,
                defaultCall: __defaultImplStub!.delegates = newValue)
        }
        
    }
```

We do not want to make `ClientDelegate` a public class (this is  a framework we are building) and we need the var to be internal so its value can easily be queried by tests. 

I see in the release notes this seems to be deliberate behaviour. Why is cuckoo making an internal var public? is there a workaround for this. I can't downgrade as i require generics support at this point

**Comment by MatyasKriz** [comment]
Hey, I just tested that issue again because of which I implemented this accessibility inheritance, but it works even without the inheritance. I'm not sure if I failed to test it properly before, but I'll revert the accessibility inheriting and add your use case to the tests so that we avoid this bug in the future.

Thanks for the report!

**Comment by andyryan** [comment]
👍 Thanks for the quick response
