### ISSUE TITLE
swift complier error with Xcode Version 10.2.1 (10E1001)

### ISSUE THREAD

**Issue by YaoXiaochuan** [Brightify/Cuckoo#294]
A small complier error in the latest version!
![屏幕快照 2019-05-31 下午5 41 05](https://user-images.githubusercontent.com/15375679/58697192-b59bd800-83cb-11e9-80a8-2e6f69c79b35.png)

**Comment by TadeasKriz** [comment]
Hey @YaoXiaochuan, could you check what `SWIFT_VERSION` is being used to compile the Cuckoo?

**Comment by YaoXiaochuan** [comment]
Swift 5

**Comment by TadeasKriz** [comment]
I think we're still on Swift 4.2 source version. Could you try switching to Swift 4.2 to compile it? Do you use CocoaPods?

**Comment by YaoXiaochuan** [comment]
I use CocoaPods to manage my dependencies and have fixed the error via Xcode auto fix functionality. Thanks!

**Comment by TadeasKriz** [comment]
I don't recommend changing the Cuckoo sources as they'll break each time you do `pod install`. Could you check your CocoaPods version? I think we have `swift_version` set to `4.2` so it should automatically use Swift 4.2 to compile Cuckoo even when your project is in Swift 5.0.

**Comment by YaoXiaochuan** [comment]
The CocoaPods version is 1.6.1.  I will switch Swift version to 4.2 as recommended.

**Comment by TadeasKriz** [comment]
CocoaPods should do that for you automatically. I'm not sure why it doesn't.

**Comment by MatyasKriz** [comment]
I'm not sure if this is still relevant in current Xcode 10.2.1. I'll close it for now, ready to be reopened if someone bumps into this issue again.
