### ISSUE TITLE
Generate mocks fails on MacOS 10.15 beta

### ISSUE THREAD

**Issue by pivotal-bolt** [Brightify/Cuckoo#296]
Trying out the new Catalina beta, Cuckoo fails to generate mocks with the following error:

```
/Users/.../Script-AEF1ECC9222069540076E39B.sh: line 6: [0: command not found
Script path: /Users/.../Carthage/Checkouts/Cuckoo
This copy of libswiftCore.dylib requires an OS version prior to 10.14.4.
Command PhaseScriptExecution failed with a nonzero exit code
```

Support for this beta is not expected, but this might be an early warning before the OS is properly released.

**Comment by TadeasKriz** [comment]
This is a problem when running with Swift < 5.1. The same thing was happening to me on a different project. Hopefully something Apple will fix before releasing Catalina.

**Comment by quetool** [comment]
I have this issue too... Isn't solved yet?

**Comment by MatyasKriz** [comment]
There's nothing to solve as far as I know. Surely you aren't using MacOS 10.15 beta?

If you've tried what @TadeasKriz suggested, please consider filing a new issue that probes your problem in more depth than just having the same issue that concerns a beta version of MacOS.

**Comment by quetool** [comment]
I have Catalina 10.15.6
![Captura de Pantalla 2020-07-30 a la(s) 12 08 12](https://user-images.githubusercontent.com/14978705/88939882-7120fc00-d25d-11ea-8223-d71a90e7421e.png)

**Comment by MatyasKriz** [comment]
@quetool. Please create a new issue and include the script you use to generate mocks.
