### ISSUE TITLE
Is there any way to create mocked object without init?

### ISSUE THREAD

**Issue by pffan91** [Brightify/Cuckoo#299]
For example, I have in my class next code:

```
    /// Block default init.
    private init() {
        fatalError("Please use init(peripheral:, queue:) instead.")
    }

    /// Initialize with connected peripheral.
    /// - parameter device: peripheral to operate with.
    /// - parameter queue: dispatch queue used to make thread safe reqad/write.
    /// - returns: created *BleServiceDriver*.
    public init(peripheral: Peripheral, queue: DispatchQueue) {
        self.peripheral = peripheral
        self.queue = queue
    }
```

I can not create `Peripheral` with something like `Peripheral.init()` (its initialization method is hidden in the library `RxBluetoothKit`). So my question - is there any way to ignore `init(peripheral: Peripheral, queue: DispatchQueue)` and receive mocked object?

**Comment by MatyasKriz** [comment]
Hey, @pffan91.

Cuckoo works by subclassing classes and implementing protocols, conjuring an `init` function would probably require some proper dependency injection. However, you may mock `Peripheral` as well and then just use that in the `init`.

**Comment by pffan91** [comment]
Great, thank you for explanation @MatyasKriz !
