### ISSUE TITLE
Generated Mocks looks different on a new machine

### ISSUE THREAD

**Issue by jakubwarchol** [Brightify/Cuckoo#302]
I just switched to a new Macbook. Same OS, Xcode and Swift version. The mocks file looks different and has multiple errors like below.
![image](https://user-images.githubusercontent.com/6187167/61953062-bb6dfe00-afb5-11e9-8f32-06249cea4636.png)

We use Carthage in the project and run 0.12.0 version of Cuckoo. Any idea what might be causing the problem?

**Comment by MatyasKriz** [comment]
Yes, as of the moment we don't have a version checking in place that would make sure the Cuckoo generator's and the Cuckoo library's version are the same. Unless the user sets the desired version of the Cuckoo Generator, the latest available generator is downloaded. The error you're seeing stems from the added support for generics that came with `1.0.0`. I recommend updating Cuckoo, there aren't any breaking changes as far as I know. However, if you're set on using the old version of `0.12.0`, use the flag `--download [VERSION]` that the `run` script provides; its usage is described in `README.md`.
