### ISSUE TITLE
Stubbing and testing closures

### ISSUE THREAD

**Issue by brandtdaniels** [Brightify/Cuckoo#310]
What is the best way to stub and test closures so you don't have to use waitUntil?

**Comment by MatyasKriz** [comment]
Hey, @brandtdaniels. As is this moment, Cuckoo doesn't yet contain the methods to make testing closures a breeze. I've been planning to add the functionality for some time (#277), but I can't find the time at the moment.
If you're up for the task, don't hesitate to write a prototype and file a PR. We'd greatly appreciate it.
