### ISSUE TITLE
How could I mock method of superclass?

### ISSUE THREAD

**Issue by MikasaAckerman** [Brightify/Cuckoo#311]
```Swift
    let mock = Mock()
    stub(mock) { (stub) in
           when(stub.callSuperClassMethod()).then...
    }
```
`callSuperClassMethod()` seems that it couldn't be mocked..?
Is there any other way to mock..?
Thank you.

**Comment by MatyasKriz** [comment]
You need to pass both file for the superclass and the class you're mocking if you want inheritance.

**Comment by MikasaAckerman** [comment]
> You need to pass both file for the superclass and the class you're mocking if you want inheritance.

Thanks for your answer.
But I'm still not understanding...
The 'pass' means add path in run script ..?
Thanks in advance..

**Comment by TadeasKriz** [comment]
Yes that's correct. Add both files as input files of the run script.

**Comment by MikasaAckerman** [comment]
Thanks for your answer.
I already added mock file and parent mock file...
But 
```Swift
    stub(mock) { (stub) in
           when(stub.callSuperClassMethod()【There is no parent method here, if I type parent method there will be error】).then...
    }
```
It couldn't call parent method in stub...

**Comment by MatyasKriz** [comment]
Show us the whole mock generation script that you're running before compilation.

**Comment by MikasaAckerman** [comment]
```shell
# Type a script or drag a script file from your workspace to insert its path.
# Define output file. Change "${PROJECT_DIR}/${PROJECT_NAME}Tests" to your test's root source folder, if it's not the default name.
OUTPUT_FILE="${PROJECT_DIR}/${PROJECT_NAME}Tests/GeneratedMocksAll.swift"
echo "Generated Mocks File = ${OUTPUT_FILE}"

# Define input directory. Change "${PROJECT_DIR}/${PROJECT_NAME}" to your project's root source folder, if it's not the default name.
INPUT_DIR="${PROJECT_DIR}/${PROJECT_NAME}"
echo "Mocks Input Directory = ${INPUT_DIR}"

# Generate mock files, include as many input files as you'd like to create mocks for.
"${PODS_ROOT}/Cuckoo/run" generate --testable "${PROJECT_NAME}" \
--output "${OUTPUT_FILE}" \
"${INPUT_DIR}/Classes/Accessor/Db/MRoutesAccessor.swift" \
"${INPUT_DIR}/Classes/Accessor/Db/DBAccessor.swift" 
# ... and so forth, the last line should never end with a backslash

# After running once, locate `GeneratedMocks.swift` and drag it into your Xcode test target group.

```

DBAccessor is parent of MRoutesAccessor, but it can't mock DBAccessor's methods in MRoutesAccessor's mock methods...

**Comment by MatyasKriz** [comment]
This seems to be correct from what I can see. Please verify that the `GeneratedMocks.swift` file has the class `MockDBAccessor` in it.

If not, wipe the whole file and run tests again. If it's still not there, the problem might be elsewhere.

**Comment by MikasaAckerman** [comment]
Thank you so much! I will check my code again and again~~~ 
It's so sorry for boring you..

**Comment by MatyasKriz** [comment]
Absolutely no problem! Although this problem might be deeper than this. I suppose you're using Xcode 10 or newer where the build system skips running some build steps if none of the input files changed. Try to include paths to your files if this problem occurs again. Other than that, I can't think of why it didn't work before wiping the file clean.

Anyway, happy mocking! 🙂
