### ISSUE TITLE
Expression type '(_, (_) throws -> _) throws -> _' is ambiguous without more context

### ISSUE THREAD

**Issue by Pubbus** [Brightify/Cuckoo#313]
Got this one again in iOS 13, xcode11. Please help.
![Screen Shot 2019-09-27 at 10 25 13 AM](https://user-images.githubusercontent.com/13481687/65739902-256b6680-e111-11e9-868e-b771bc3443ce.png)

_Originally posted by @VuongTranCong in https://github.com/Brightify/Cuckoo/issues/219#issuecomment-535770995_

**Comment by Pubbus** [comment]
I've got the same issue. I can't reopen the issue so I create a new one here. Don't know if it is a swift bug.

**Comment by MatyasKriz** [comment]
Hey, I'm sorry for only trying to reproduce this now, after you've filed a PR and changed the code according to my wishes.

I am unable to get this error on Xcode 11.2. What version are you using? And could you please provide me with the class being mocked that causes this problem?

I have nothing against specifying the return type, however, I'd rather avoid this added complexity if it is not completely necessary.

Thank you in advance.

**Comment by MatyasKriz** [comment]
Alright, I take that back. When switching between master and the PR, I get errors. Although I don't understand it completely yet. Please be patient with me, I don't want to merge changes that I don't fully comprehend how they affect the functioning of Cuckoo/Generator.

**Comment by Pubbus** [comment]
Yeah, make sure that you are checking out a clean master, remove cuckoo_generator as well (make sure that we are not using a generated one from the fixed PR).
