### ISSUE TITLE
Prefix mock- and stubnames

### ISSUE THREAD

**Issue by emielv** [Brightify/Cuckoo#321]
Hi all,

My team wants to slowly integrate the Cuckoo framework into our project for generating mocks. We want to support tests that still use our own mocks and new / refactored tests that use Cuckoo mocks. The problem we are facing is that there are conflicts between mocks we wrote ourselves and mocks that Cuckoo generates e.g. same classname for the mocks and it also reduces readability because it’s not immediately obvious if you are working with Cuckoo mocks or not. 
Is it possible / is there a way to add a prefix to the classnames of the generated mocks e.g. generating a mock for protocol Abc will generate CuckooMockAbc / CKMockAbc?

Thanks in advance!

**Comment by MatyasKriz** [comment]
Hey, that's not a bad idea. I'd welcome a PR that would implement this to make one's life easier.

You need to start by running `make dev` in project root, which creates generator project file for the Cuckoo workspace.

I think you'd have to edit `GenerateMocksCommand.swift` and define a command named "mock-prefix" perhaps that would register the prefix given by user, optional all the way to the mocks generation and then either using that or the default "Mock".

Let me know if you get stuck or need some clarification, I'll be happy to help.

**Comment by emielv** [comment]
Hello @MatyasKriz ,
I created a PR regarding this feature and would love some feedback.

Thanks!
