### ISSUE TITLE
Escape reserved keywords

### ISSUE THREAD

**Issue by paiv** [Brightify/Cuckoo#328]
Trying to mock protocols with escaped reserved keywords:
```swift
protocol Example {
    func `nil`() -> Void
}
```

Generates a mock with compilation errors like:

```swift
     func nil()  {
//        ^
// Keyword 'nil' cannot be used as an identifier here
```

**Comment by mwoollard** [comment]
I'm effected by this so am going to take a look at resolving.

**Comment by MatyasKriz** [comment]
Thanks to @sk409 for implementing this! This change will be included in the next release, though I'll close the issue so I don't forget. 🙂
