### ISSUE TITLE
Runtime error with v1.3.0 and Swift 5.0

### ISSUE THREAD

**Issue by vikytech** [Brightify/Cuckoo#331]
I am trying to use the latest version of library(1.3.0) since I am already using Swift 5.0, but I am getting the below error when I run the tests.

Xcode Version: **11.3.0**
Swift version: **5.0**

```
2020-01-27 16:35:42.999141+0530 mocker[45528:966664] Launching with XCTest injected. Preparing to run tests.
2020-01-27 16:35:43.039552+0530 mocker[45528:966664] Failed to load test bundle from file://~/Library/Developer/Xcode/DerivedData/mocker-dycjgannhunhhibnccfljkqhsvtj/Build/Products/Debug-iphonesimulator/mocker.app/PlugIns/mockerTests.xctest/: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(~/Library/Developer/Xcode/DerivedData/mocker-dycjgannhunhhibnccfljkqhsvtj/Build/Products/Debug-iphonesimulator/mocker.app/PlugIns/mockerTests.xctest/mockerTests): Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: ~/Library/Developer/Xcode/DerivedData/mocker-dycjgannhunhhibnccfljkqhsvtj/Build/Products/Debug-iphonesimulator/mocker.app/PlugIns/mockerTests.xctest/mockerTests
  Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=~/Library/Developer/Xcode/DerivedData/mocker-dycjgannhunhhibnccfljkqhsvtj/Build/Products/Debug-iphonesimulator/mocker.app/PlugIns/mockerTests.xctest/mockerTests, NSDebugDescription=dlopen_preflight(~/Library/Developer/Xcode/DerivedData/mocker-dycjgannhunhhibnccfljkqhsvtj/Build/Products/Debug-iphonesimulator/mocker.app/PlugIns/mockerTests.xctest/mockerTests): Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: ~/Library/Developer/Xcode/DerivedData/mocker-dycjgannhunhhibnccfljkqhsvtj/Build/Products/Debug-iphonesimulator/mocker.app/PlugIns/mockerTests.xctest/mockerTests
  Reason: image not found, NSBundlePath=~/Library/Developer/Xcode/DerivedData/mocker-dycjgannhunhhibnccfljkqhsvtj/Build/Products/Debug-iphonesimulator/mocker.app/PlugIns/mockerTests.xctest, NSLocalizedDescription=The bundle “mockerTests” couldn’t be loaded because it is damaged or missing necessary resources.}
2020-01-27 16:35:43.039908+0530 mocker[45528:966664] Waiting to run tests until the app finishes launching.
2020-01-27 16:35:43.207868+0530 mocker[45528:966664] The bundle “mockerTests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2020-01-27 16:35:43.207968+0530 mocker[45528:966664] (dlopen_preflight(~/Library/Developer/Xcode/DerivedData/mocker-dycjgannhunhhibnccfljkqhsvtj/Build/Products/Debug-iphonesimulator/mocker.app/PlugIns/mockerTests.xctest/mockerTests): Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: ~/Library/Developer/Xcode/DerivedData/mocker-dycjgannhunhhibnccfljkqhsvtj/Build/Products/Debug-iphonesimulator/mocker.app/PlugIns/mockerTests.xctest/mockerTests
  Reason: image not found) 
```

@TadeasKriz / Anyone else Please help me resolve this issue

**Comment by thaoth58** [comment]
I have the same problem.

**Comment by TadeasKriz** [comment]
Are you sure this is caused by Cuckoo? It seems like a dependency manager not being configured correctly. Are you using CocoaPods?

**Comment by thaoth58** [comment]
Yes. 
Maybe it is not Cuckoo issue. 
I'm just trying to find some solution :D

**Comment by TadeasKriz** [comment]
Seems like a misconfiguration in your dependencies. Make sure you have search paths and embedded frameworks set correctly. Also make sure you have the tests target as a child target in your Podfile (see CocoaPods readme for more info).

**Comment by vikytech** [comment]
> Seems like a misconfiguration in your dependencies. Make sure you have search paths and embedded frameworks set correctly. Also make sure you have the tests target as a child target in your Podfile (see CocoaPods readme for more info).

@TadeasKriz 
I tried integrating Cuckoo(1.2.0) with my current repo,and it works fine.
But when it is upgraded to 1.3.0 I am getting this error.

Please let me know if anything else has to be configured specifically in 1.3.0 version.

**Comment by thaoth58** [comment]
@vikytech 
Thank you. I tried version 1.2.0 and it works fine too. 
Waiting for some help to be able to use v1.3.0  (Swift 5)

**Comment by easenliao** [comment]
I have the same problem.

**Comment by TadeasKriz** [comment]
I was able to reproduce this issue, but even when I tried `Cuckoo 1.2.0` or without it altogether. Could it be an issue with CocoaPods?

**Comment by mugabe** [comment]
Same issue.
Created new project with stub XCTest, just added `pod 'Cuckoo'` without run phase, run test and got same error.

**Comment by MatyasKriz** [comment]
Hey, along with @TadeasKriz we found the culprit and banished it for good. @vikytech, @thaoth58, @easenliao, @mugabe; please try version `1.3.2`, it should work for you now.

Please let me know if it works for you so we can close this issue and otherwise try to see what else could cause this.

**Comment by vikytech** [comment]
@MatyasKriz & @TadeasKriz 
Thanks you so much for fixing it.
It works like a charm now :-).

Can you release `1.3.2` as pod version in CocoaPods?

Currently installed and checked using github as source:
```pod "Cuckoo", :git => 'https://github.com/Brightify/Cuckoo.git'```

**Comment by vikytech** [comment]
If @thaoth58 / @easenliao  / @mugabe can verify in your machine & project we can happily close this issue

**Comment by thaoth58** [comment]
@vikytech 
Everything is fine with that version. Waiting for cocoapods

**Comment by easenliao** [comment]
@vikytech 
Thx. It works for me

**Comment by MatyasKriz** [comment]
I was wondering what releasing `1.3.2` meant, of course it is released. Apparently it has been moved to CDN, so you need to run `pod update Cuckoo` to switch and correctly update to `1.3.2`.

**Comment by vikytech** [comment]
@MatyasKriz Sure thanks , It works now
