### ISSUE TITLE
OCMock with Swift Package Manager

### ISSUE THREAD

**Issue by mRs-** [Brightify/Cuckoo#335]
Is there a plan to use OCMock with Swift Package Manager? Would be awesome to stub Apples Objective-C classes with Cuckoo via SPM 😀

**Comment by TadeasKriz** [comment]
Hi, unless OCMock is available through SwiftPM, I'd think this wouldn't be possible.

**Comment by mRs-** [comment]
Okay, will take care of getting OCMock in SwiftPM then 😀

**Comment by mRs-** [comment]
It seems there is already a Pull Request at OCMock https://github.com/erikdoe/ocmock/pull/379. I reached out to them. Maybe we can get some traction there 👍

**Comment by mRs-** [comment]
Pull Request on OCMock is coming in https://github.com/erikdoe/ocmock/pull/442

**Comment by MatyasKriz** [comment]
Hey, @mRs-. Thanks for the update!

**Comment by mRs-** [comment]
Is it possible to fork OCMock for the time being and add the revision to SPM? Like Firebase is doing this? https://github.com/firebase/firebase-ios-sdk/blob/master/Package.swift#L123

**Comment by MatyasKriz** [comment]
Hey, @mRs-. Thanks for the update on this and proposed temporary solution. I don't see an issue with this as long as the SPM-added OCMock works fine with Cuckoo.
What do you think, @TadeasKriz ?

**Comment by kainjow** [comment]
https://github.com/erikdoe/ocmock/pull/442 was abandoned in favor for https://github.com/erikdoe/ocmock/pull/460 which was merged: https://github.com/erikdoe/ocmock/blob/master/Package.swift

**Comment by MatyasKriz** [comment]
Thank you for the update. 🙂 So I suppose nothing prevents us to implement support for OCMock with SwiftPM now.

**Comment by MatyasKriz** [comment]
I've managed to integrate OCMock as an SPM dependency, so it will be available for both SPM and CocoaPods out of the box with next release.
