### ISSUE TITLE
Slack invitation link is broken

### ISSUE THREAD

**Issue by thomasMinshull** [Brightify/Cuckoo#339]
Hey just tried to join the slack and this link in the Read Me to the slack workspace invitation is broken. :( 
 
https://swiftkit.brightify.org/

it's returning a 502.

**Comment by MatyasKriz** [comment]
Hey, @thomasMinshull. It has been down for quite some time and I'm not sure where the problem is as I'm not the one who takes care of it. @TadeasKriz might be able to shed some light on this issue.

**Comment by thomasMinshull** [comment]
Thanks for following up @MatyasKriz,

I'll follow up with @TadeasKriz

**Comment by TadeasKriz** [comment]
Hey @thomasMinshull, the link was previously backed by a tool that is no longer developed and seems to get broken by a Slack API update. We'll be opening up our company discourse instance to the public to support our OpenSource projects and sunsetting the Slack channel in the near future.

In the meantime, please use the GitHub issues as a means of communication with our team.

**Comment by thomasMinshull** [comment]
Thanks for following up so quickly

**Comment by fevicks** [comment]
@thomasMinshull @MatyasKriz Is there any way to join in your slack :)

**Comment by MatyasKriz** [comment]
@fevicks please use GitHub issues before the Slack inviter is functional again.
