### ISSUE TITLE
Verify with generic return value

### ISSUE THREAD

**Issue by mgray88** [Brightify/Cuckoo#345]
As far as I can tell it's not a simple matter to verify a function call where that function is generic and the type is inferred from the return value.

e.g.
```swift
class Coupon: Codable, Persistable { }

func get<T: Codable & Persistable>(forKey defaultName: String) -> T?
```
Where `get` is expected to return a `Coupon`:
```swift
verify(persistence).get(forKey: equal(to: "key"))
```
We get `Generic parameter 'T' could not be inferred`

The only solution is to assign the `DoNotUse` struct from the `VerificationProxy` to an unused variable:
```swift
let _: Cuckoo.__DoNotUse<(String), Coupon?> =
    verify(persistence).get(forKey: equal(to: "key"))
```
Which, while it works, is a bit clunky.

Maybe a solution could be to have a `CallMatcher` which allows specifying the return value, or at least the return type?

**Comment by MatyasKriz** [comment]
Hey, sorry I didn't get around to this until now.

Do you have some working implementation of the custom matcher that would work?

**Comment by mgray88** [comment]
I don't sorry. That solution was the best I was able to come up with in the time I had

**Comment by mgray88** [comment]
Stealing an idea from mockk:

```swift
extension __DoNotUse {
    func hint(_ returnType: OUT.Type) { }
}
```

I can now do:
```swift
verify(persistence).get(forKey: equal(to: "key")).hint(Coupon?.self)
```

**Comment by MatyasKriz** [comment]
Hey, that's pretty nice. I'd name it something like `.returning(_:)` or `with(returnType:)`, but I'll credit you with the ~thievery~ great observation skills.
Alternatively, you can create a PR yourself, so you'll be among the contributors of Cuckoo.
@TadeasKriz might want to weigh in on this being added to public API.

**Comment by RamiroRamirez** [comment]
is there any plan to release a version, including this fix, soon?

**Comment by mgray88** [comment]
@RamiroRamirez Is it not in there? It's in the Readme
https://github.com/Brightify/Cuckoo#verification

**Comment by MatyasKriz** [comment]
This is actually my bad as I forgot to release a version including this PR.

Though, @RamiroRamirez, you can use `master` in the meantime.

**Comment by MatyasKriz** [comment]
Sorry for this, I haven't really been able to find time to properly maintain this project for some time, but I'll try to release a new version today.
