### ISSUE TITLE
Contents of GeneratedMocks.swift file is not updated when the input files are changed

### ISSUE THREAD

**Issue by thomasMinshull** [Brightify/Cuckoo#346]
I'm having difficulty regenerating the mocks for my project (from a build script) so they reflect the latest changes to the input files

I am currently running cuckoo with cocoapods. 
I have the following build script in my testTarget build script: 

```
# Define output file. Change "${PROJECT_DIR}/${PROJECT_NAME}Tests" to your test's root source folder, if it's not the default name.
OUTPUT_FILE="${PROJECT_DIR}/${PROJECT_NAME}Tests/Mocks/GeneratedMocks.swift"

echo "Generated Mocks File = ${OUTPUT_FILE}"

# Define input directory. Change "${PROJECT_DIR}/${PROJECT_NAME}" to your project's root source folder, if it's not the default name.
INPUT_DIR="${PROJECT_DIR}/${PROJECT_NAME}"
echo "Mocks Input Directory = ${INPUT_DIR}"

# Generate mock files, include as many input files as you'd like to create mocks for.
"${PODS_ROOT}/Cuckoo/run" generate --testable "${PROJECT_NAME}" \
--output "${OUTPUT_FILE}" \
"${INPUT_DIR}/SomeDirectory/someFile.swift"
# ... and so forth, the last line should never end with a backslash

# After running once, locate `GeneratedMocks.swift` and drag it into your Xcode test target group.
```

I've run this build script, generated `GeneratedMockes.swift` and added this to my project. 
Now when I modify the input file and re-build the testTarget the GeneratedMocks do not get updated to reflect the changes. 

I've attempted to delete the OUTPUT_FILE by adding the `rm $OUTPUT_FILE` to the build script
 
```
# Define output file. Change "${PROJECT_DIR}/${PROJECT_NAME}Tests" to your test's root source folder, if it's not the default name.
OUTPUT_FILE="${PROJECT_DIR}/${PROJECT_NAME}Tests/Mocks/GeneratedMocks.swift"

# Deletes the contents of the output file 
rm $OUTPUT_FILE
echo "Delete Generated Mocks File = ${OUTPUT_FILE}"

echo "Generated Mocks File = ${OUTPUT_FILE}"

# Define input directory. Change "${PROJECT_DIR}/${PROJECT_NAME}" to your project's root source folder, if it's not the default name.
INPUT_DIR="${PROJECT_DIR}/${PROJECT_NAME}"
echo "Mocks Input Directory = ${INPUT_DIR}"

# Generate mock files, include as many input files as you'd like to create mocks for.
"${PODS_ROOT}/Cuckoo/run" generate -d --testable "${PROJECT_NAME},NearVehicle,CommonTools" \
--output "${OUTPUT_FILE}" \
"${INPUT_DIR}/CommonArchitecture/Store/VehicleBLEStore.swift" \
"${INPUT_DIR}/CommonArchitecture/Store/RDataStore.swift" \
"${INPUT_DIR}/CommonArchitecture/Store/PersistenceManager.swift" \
"${INPUT_DIR}/CommonArchitecture/Models/DataModels/MainModel.swift" \
"${INPUT_DIR}/CommonArchitecture/Coordinators/Dependencies.swift" \
"${INPUT_DIR}/../../Core/Core/CommandControllerProvider/CommandControllerProvider.swift" \
"${INPUT_DIR}/CommonArchitecture/Services/VehicleStateAggregator.swift" \
"${INPUT_DIR}/../../NearVehicle/NearVehicle/BLE/BLEManager.swift" \
"${INPUT_DIR}/../../CommonTools/CommonTools/Utilities/NetworkConnectivityHandler.swift" \
"${INPUT_DIR}/DomainArchitecture/Vehicle/Vehicle/VehicleClosures/ViewModels/ClosureButtonVMBases/ClosureButtonVMDelegate.swift" \
"${INPUT_DIR}/../../CommonTools/CommonTools/Utilities/AppDebugOptionsController.swift" \
"${INPUT_DIR}/../../CommonTools/CommonTools/Common/UserDataHandlerType.swift"
# ... and so forth, the last line should never end with a backslash

# After running once, locate `GeneratedMocks.swift` and drag it into your Xcode test target group.
```
And the GeneratedMocks.swift is regenerated without reflecting the latest changes.

**Comment by thomasMinshull** [comment]
I've also tried passing the `-d` so that the code generation was run in debug mode. And that had no effect.

**Comment by MatyasKriz** [comment]
Hey, @thomasMinshull. Does running a clean build regenerate the file correctly?

**Comment by thomasMinshull** [comment]
@MatyasKriz that worked, cleaning the build does regenerate the file correctly. 
That's great now I just have to see if I can trigger a cleaning of the build folder in my build script

**Comment by MatyasKriz** [comment]
@thomasMinshull alright, then make sure that the "Output Files" path is correct, from my understanding Xcode skips over the build phase because it deems it irrelevant.
By the way, what Xcode version are you using?

**Comment by thomasMinshull** [comment]
I was able to fix this, this morning. I was not explicitly listing my input files in the input files section of the build script. I assumed this would not be an issue, because the script runs in either case, and I was wrong. 

With the input files explicitly listed here or in a xcfilelist the mocks are generated correctly. 

Thanks for your help

**Comment by MatyasKriz** [comment]
@thomasMinshull glad you found a solution. 🙂 Thanks for letting me know; I'll add this bit of information into the readme in case anyone encounters this problem as well.
