### ISSUE TITLE
Add support for input files being supplied from xcode's Build Phase input file list 

### ISSUE THREAD

**Issue by thomasMinshull** [Brightify/Cuckoo#348]
I've just updated to 1.4.0 to take advantage of the support of XCode Input Files for inputs. It would be great to have support for Input File Lists as well. 

Thanks for keeping on top of these new features

**Comment by MatyasKriz** [comment]
Hey, @thomasMinshull. As far as I know, xcfilelist is only for Xcode to know which files to monitor. Using that as an input would severely limit mock generating (globs and regex would be out of the question).

Personally, I'd go about it the other way. It would be ideal if Cuckoo generator could collect all the filenames that it's working with (which it already does) and generate an xcfilelist at specified path every time it's run if it's desired.

**Comment by TadeasKriz** [comment]
Xcode has a bug (I'd think it's a bug) where changing the xcfilelist triggers a complete rebuild as if you did "clean" and "build".
