### ISSUE TITLE
Xcode 12 beta issue

### ISSUE THREAD

**Issue by shtnkgm** [Brightify/Cuckoo#350]
In the latest Xcode12beta, the following error occurs on the Carthage build and this The library could not be built, Carthage's error log is below.

```bash
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/shtnkgm/Desktop/aaaaa/bbbbb/Carthage/Checkouts/Cuckoo/Cuckoo.xcodeproj -scheme Cuckoo-iOS -configuration Release -derivedDataPath /Users/shtnkgm/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A6163b/Cuckoo/1.4.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/62/nrp34pc96t550_hhml86hmwrr_q2rc/T/Cuckoo SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/shtnkgm/Desktop/aaaaa/bbbbb/Carthage/Checkouts/Cuckoo)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/62/nrp34pc96t550_hhml86hmwrr_q2rc/T/carthage-xcodebuild.2lRxtD.log
make: *** [make] Error 1
```

The error log for the xcodebuild command is as follows

```bash
Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in MockManager.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

===
environment

macOS 10.15.5
Xcode Version: 12 beta 2
Cuckoo Version: 1.4.1
Carthage: 0.34.0

**Comment by shtnkgm** [comment]
related issue

Undefined symbol: type metadata for Swift._StringObject.Variant
https://developer.apple.com/forums/thread/649918

**Comment by MatyasKriz** [comment]
Hey, @shtnkgm. Thanks for bringing this issue to our attention. We haven't been trying to compile Cuckoo in any of the `Xcode 12` beta versions, so it might not be compilable.

We will monitor this and step in if the issue stays with us until GM, for the moment, I don't feel the need to fix what Xcode broke, please use `Xcode 11` for now if possible.

If not however, a PR that would fix the Xcode breakage would get merged into a secluded `fix/Xcode12-beta` branch which would then get updated with the latest Cuckoo features and fixes until `Xcode 12 GM` comes out.

**Comment by intere** [comment]
I'm seeing the same issue trying to build dependencies through Carthage with Xcode 12 beta 2 and beta 3.  Related: https://developer.apple.com/forums/thread/649918
