### ISSUE TITLE
Testing API calls

### ISSUE THREAD

**Issue by quetool** [Brightify/Cuckoo#353]
Hi, I need to make UT for api call and I read async methods are not supported yet, am I correcto? Anyway, I am doing it this way (would love to know if it is a correct implementation)

```
func testGetAllBeersStatusCode200() {
    // given
    var sut = MockApiClient()
    let expectation = XCTestExpectation(description: "Performs a request")
    
    // when
    stub(sut) { (stub) in
        when(stub.getAllBeers(byFood: "", fromPage: 1, perPage: anyInt(), completion: anyClosure())).thenCallRealImplementation()
    }
    sut.getAllBeers(byFood: "", fromPage: 1, perPage: 20) { (response) in
        XCTAssertEqual(response.response?.statusCode, 200)
        expectation.fulfill()
    }
    
    // then
    wait(for: [expectation], timeout: 0.5)
}
```

**Comment by MatyasKriz** [comment]
Hey, @quetool. Yes, async methods haven't been added yet, so you need to use whatever XCTest offers.

I'm not very well-versed in async testing, so I can't say for sure, but your approach looks good to me, does it work?

**Comment by quetool** [comment]
Well, that depends on what do you mean with "works" :P
Test passes, but I wasn't sure I was doing it right! Thanks!
