### ISSUE TITLE
Undefined symbol: [...]

### ISSUE THREAD

**Issue by quetool** [Brightify/Cuckoo#357]
Hi! We can say this is a continuation of this issue https://github.com/Brightify/Cuckoo/issues/356
After modifying the Run Script with absolute paths instead environment variable I was able to build my tests and generate GeneratedMocks.swift file but now I have a lot of other issues...

![Captura de Pantalla 2020-07-30 a la(s) 14 39 01](https://user-images.githubusercontent.com/14978705/88955679-9d934300-d272-11ea-90b9-0988ceb4db8e.png)

**Comment by MatyasKriz** [comment]
I must say, @quetool, your errors are something that I haven't come across in my years of Cuckoo maintenance and iOS development.

Please make sure your Cocoapods is updated and 
```
rm -rf Pods
```
then install pods again and let me know if anything changed.

**Comment by quetool** [comment]
> I must say, @quetool, your errors are something else. I haven't come across any of this in my years of Cuckoo maintenance and iOS development even once.
> 
> Please make sure your Cocoapods is updated and
> 
> ```
> rm -rf Pods
> ```
> 
> then install pods again and let me know if anything changed.

There is a first time for everything ;)
I will do what you suggest...

**Comment by quetool** [comment]
So, I deleted Pod folder and also deleted DerivedData content and I got the same...
Could be some kind of conflict with other Pods? e.g. OCMockito? 
If you need the full build log let me know...

**Comment by MatyasKriz** [comment]
Could you please try creating a fresh project with just Cuckoo, so we can be sure there are no other factors involved?

`OCMock` shouldn't have any effect, I always test Cocoapods, Carthage, and SPM before releasing new version.

If a fresh project does the same thing, I'd ask you to send it over to me, I'll probably have some time during the weekend to take a look at it.

**Comment by quetool** [comment]
Ok I solved it (if you can explain me why this was happening I would appreciate)

this was my Podfile before
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def mibanco_pods
    pod 'AFNetworking', '~> 3.2.1'
    pod 'PureLayout'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'GoogleTagManager'
    pod 'Flurry-iOS-SDK/FlurrySDK'
    pod 'NewRelicAgent'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'MaterialComponents/Buttons'
    pod "Cuckoo"
    pod 'Cuckoo/OCMock'
end

target "MiBancoDev" do
    mibanco_pods
end

target "MiBancoObjCTests" do
  mibanco_pods
  inherit! :search_paths
  use_frameworks!
  pod 'OCMockito', '~> 5.0'
end
```

Then I changed to this
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def mibanco_pods
    pod 'AFNetworking', '~> 3.2.1'
    pod 'PureLayout'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'GoogleTagManager'
    pod 'Flurry-iOS-SDK/FlurrySDK'
    pod 'NewRelicAgent'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'MaterialComponents/Buttons'
end

target "MiBancoObjCTests" do
  mibanco_pods
  inherit! :search_paths
  use_frameworks!
  pod 'OCMockito', '~> 5.0'
  pod "Cuckoo"
  pod 'Cuckoo/OCMock'
end

target "MiBancoSwiftTests" do
  mibanco_pods
  inherit! :search_paths
  use_frameworks!
  pod "Cuckoo"
end
```

And build succeeded

(As you can see, I am trying to use Cuckoo cause I have a project written both with objective c and swift and I want to use Cuckoo to write tests for both languages)

**Comment by MatyasKriz** [comment]
You added the Swift tests target? I think this might have been an issue of adding Cuckoo to a non-test target.

I'll close the issue, but we can discuss it further.

**Comment by quetool** [comment]
Yep, not only, at first I added the pods to the main `mibanco_pods` target. That way it was showing me the errors described here
So, I remove the pods from `mibanco_pods` and moved like you can see on the right side of this image

Before / After
![Captura de Pantalla 2020-07-31 a la(s) 15 27 27](https://user-images.githubusercontent.com/14978705/89065687-86bc2180-d342-11ea-993f-736a6bdfbb76.png)

Of course, in the picture is missing the declaration for the main target
```
target "MiBancoDev" do
    mibanco_pods
end
```

**Comment by srikanthzm** [comment]
I tried adding Cuckoo in Tests target[Unit Testing], it works.

But If I try to add it in UI testing, I face the same issue. Won't cuckoo work in UI Testing target. 

I'm using `Cuckoo (1.5.1):` version

> target 'Demo' do
  use_frameworks!
  target 'DemoUITests' do
    pod "Cuckoo"
  end
end
