### ISSUE TITLE
mocking Objective C view controller

### ISSUE THREAD

**Issue by quetool** [Brightify/Cuckoo#360]
Hi! Maybe this isn't related to Cuckoo but I don't know where to ask.
What could be the reason why I can mock an Objective C view controller but can't mock another one?

AccountStatementViewController is an ObjC class, his header file is:
```
#import <UIKit/UIKit.h>

@interface AccountStatementViewController : UIViewController

@property (strong, nonatomic) UITableView *tableView;
@property (copy, nonatomic) void(^dismissBlock)(void);

@end
```
And I get this error
![Captura de Pantalla 2020-07-31 a la(s) 16 54 50](https://user-images.githubusercontent.com/14978705/89072385-d7397c00-d34e-11ea-8685-6bcd0e248572.png)

AccountsViewController is either an ObjC class, his header file is:
```
#import <UIKit/UIKit.h>

@interface AccountsViewController : UIViewController

@property (strong, nonatomic) UICollectionView *collectionView;
@property (strong, nonatomic) MBCollectionViewFlowLayout *flowLayout;

@property (strong, nonatomic) NSArray *dataSource;
@end
```
But this one I can mock it fine
![Captura de Pantalla 2020-07-31 a la(s) 16 55 03](https://user-images.githubusercontent.com/14978705/89072392-da346c80-d34e-11ea-88be-2fb561bf957f.png)

**Comment by quetool** [comment]
My bad, AccountStatementViewController.h was missing from bridging header (I feel so dumb)

**Comment by MatyasKriz** [comment]
Don't worry, happens to the best of us. 🙂
