### ISSUE TITLE
Verify with order in sequence

### ISSUE THREAD

**Issue by ionini** [Brightify/Cuckoo#361]
Forgive me if this is not the place to post this, but I am trying to verify that some methods are being called in a specified sequence and I am not finding how to do it.
For example:
This is equivalent:
```swift
verify(analytics, times(1)).sendEvent("start")
verify(analytics, times(1)).sendEvent("stop")
```
to this:
```swift
verify(analytics, times(1)).sendEvent("stop")
verify(analytics, times(1)).sendEvent("start")
```

I would like to have something like Mockito's `InOrder`.

**Comment by MatyasKriz** [comment]
Hey, @ionini. This is certainly the place to post this. `InOrder` has been requested, but not implemented. I'll close this issue in favor of #34, you can monitor progress there.

If you feel like it, adding it yourself shouldn't prove too difficult and it would be greatly appreciated!
