### ISSUE TITLE
How to mock ProcessInfo?

### ISSUE THREAD

**Issue by xareelee** [Brightify/Cuckoo#375]
I want to make `ProcessInfo.processInfo.environment[key]` return specific values when testing. 

How can I achieve that with Cuckoo? It's hard to find a sample code. Most of them use dependency injection with adopting protocols.

**Comment by MatyasKriz** [comment]
Hey, @xareelee. Cuckoo depends on having the source code on hand to generate the mocking classes as needed. `ProcessInfo` might be mockable using the OCMock integration, so take a look at the tests and try that.

**Comment by mugabe** [comment]
You can do it in swifty way without OCMock.

At first, to keep your code testable you should not use `ProcessInfo.processInfo` directly, but pass it  as dependency to your class.
e.g.:
```swift
class App {
    init(processInfo: ProcessInfo) {
        if (processInfo.environment["help"] != nil) {
            printHelp()
        }
    }
}
App(processInfo: ProcessInfo.processInfo)
```

Then you can describe your own protocol that `ProcessInfo` should conform.
```swift
protocol ProcessInfoProtocol {
    var environment: [String : String] { get }
}
extension ProcessInfo: ProcessInfoProtocol { }
```

Now you can replace dependency type of your class to `ProcessInfoProtocol` and pass own implementation or Cuckoo's mock.
