### ISSUE TITLE
Protocol Composition Mock

### ISSUE THREAD

**Issue by SeamusY** [Brightify/Cuckoo#379]
I was writing a piece of code that requires a "Protocol Composition"
`InteractionServiceHandler & NavigationContentCaller`

But it seems that the Cuckoo only support single Protocol, is the feature supported for the composition ?

Information provide from:
https://docs.swift.org/swift-book/LanguageGuide/Protocols.html#//apple_ref/doc/uid/TP40014097-CH25-ID282

**Comment by SeamusY** [comment]
I just ended up building a class inheriting the two types
`class Mocker: InteractionServiceHandler, NavigationContentCaller ` which does the job. Although not preferable.

**Comment by MatyasKriz** [comment]
We should add support for this. Not very common but definitely a good thing to have.

**Comment by MatyasKriz** [comment]
Fixed in 2.0.3. Thanks for the issue!
