### ISSUE TITLE
"Cannot find XCTFail in scope" build error on Xcode 12.5

### ISSUE THREAD

**Issue by earthling-shruti** [Brightify/Cuckoo#380]
Building Cuckoo on Xcode 12.5 fails because 'XCTFail' is not available in scope in the `MockManager.swift` file.
Workaround: Commenting out the `XCTFail` line allows the build to succeed.
Edit: Adding XCTest framework to the project seems to let be build pass as well.

**Comment by Veeit** [comment]
I have the same issue, but adding XCTests to the project isn't the solution for me

**Comment by anand-kulk** [comment]
What was the resolution? I am still having this on Xcode 16, adding XcTest framework to build settings for Tests project still doesn't solve it...

**Comment by MatyasKriz** [comment]
@anand-kulk that's weird, when adding the framework to the test target everything should work correctly. Please try it in a new project and then compare your build settings, perhaps linker options are different?
