### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by pawee-del** [Brightify/Cuckoo#385]
i paste the script in xcode, but when running it says permission denied : 
![image](https://user-images.githubusercontent.com/72118587/113992346-b4287a00-9896-11eb-965e-150e3e5e94cc.png)
****

**Comment by alexfu** [comment]
I encountered a similar issue and it ended up being because there was a trailing space after a backslash.

```diff
- "${INPUT_DIR}/path/to/file.swift" \ 
+ "${INPUT_DIR}/path/to/file.swift" \
```

**Comment by MatyasKriz** [comment]
Hey, @pawee-del. Did @alexfu's help work?
