### ISSUE TITLE
Multiline Protocol Composition return value

### ISSUE THREAD

**Issue by stonko1994** [Brightify/Cuckoo#386]
When there is a 'Multiline Protocol Composition' return value the generated code contains syntax errors and the project won't build.

```swift
internal protocol FooBar {
    func foo(
    ) -> (
        A &
        B &
        C &
        D
    )
}
```

The above protocol will result in the following generated `Mock`:
![Screenshot 2021-04-13 at 15 37 03](https://user-images.githubusercontent.com/6216959/114561739-1d7d0400-9c6e-11eb-918b-e1cc97128d7f.png)

I wasn't able to find a workaround except keeping that on the same line (and disable the `SwiftLint` line length rule for this 😬)

--- 
EDIT:

#379 Is kinda related but not needed.

**Comment by MatyasKriz** [comment]
I see, this is curious. Though a pretty easy fix. Thanks for the report. 🙂

**Comment by rolandkakonyi** [comment]
@MatyasKriz It seems this was fixed by https://github.com/Brightify/Cuckoo/releases/tag/1.8.0

**Comment by MatyasKriz** [comment]
Thanks for letting me know, @rolandkakonyi. 🙂 I thought I saw an issue like this. 😄
