### ISSUE TITLE
library not found for -lswiftXCTest in Xcode 12.5

### ISSUE THREAD

**Issue by soucolline** [Brightify/Cuckoo#387]
Hello, since i've updated Xcode to 12.5 Cuckoo fails immediately with an error :
```library not found for -lswiftXCTest```

Is there something to be done framework side or could it be a bug from Xcode ?

**Comment by thatswinnie** [comment]
Same here. The build flags need to be changed from 
`'OTHER_LDFLAGS' => '$(inherited) -weak-lswiftXCTest',`
to 
`'OTHER_LDFLAGS' => '$(inherited) -weak-lXCTestSwiftSupport',`
in the podspec according to this post: https://github.com/Quick/Nimble/issues/855

**Comment by TadeasKriz** [comment]
Thank you for looking into this! Do you want to submit a PR with a fix?

**Comment by TadeasKriz** [comment]
I'll go ahead and do the change myself and release a new version. We'll then have to check if the `-weak-lXCTestSwiftSupport` works with older Xcode versions.

**Comment by thatswinnie** [comment]
I just created the PR: https://github.com/Brightify/Cuckoo/pull/389

**Comment by TadeasKriz** [comment]
Oh, I see @thatswinnie already made a PR, that's wonderful!

**Comment by TadeasKriz** [comment]
Unfortunately I'm unable to release a new version on my machine (CocoaPods misconfigured on M1 Mac) and will have to wait for my colleague to release it tomorrow. In the meantime, please try using the `master` if you need it. And if some of you still have Xcode 12.4 (or older), please try the `master` branch with it to see if we'll need more changes to be backward compatible. Thanks a lot for your help!

**Comment by soucolline** [comment]
I've tested on 12.4 and 12.5 and it's working with the master branch 👍

**Comment by thatswinnie** [comment]
It's working for me as well on both Xcode versions (12.4 & 12.5). Thanks @TadeasKriz !

**Comment by TadeasKriz** [comment]
Thanks to you @thatswinnie for the PR!

**Comment by sudheertreddy** [comment]
What is the fix? I am still having this issue.
