### ISSUE TITLE
Upgrade to OCMock >= 3.8.1 in podspec for ARM compatibility?

### ISSUE THREAD

**Issue by underbjerg** [Brightify/Cuckoo#393]
Hi,

The current version of OCMock used by Cuckoo/OCMock is very old (version 3.4.3), and has issues on Apple Silicon and Xcode 11 (among other things).

It would be great if Cuckoo's version of OCMock could be upgraded to >= 3.8.1 which works on Apple Silicon (release notes: https://ocmock.org/download/).

//Erik

**Comment by MatyasKriz** [comment]
Yeah, that sounds like a good idea.

**Comment by MatyasKriz** [comment]
Pushed to `master`, but not yet released as it doesn't warrant its own release IMO.
