### ISSUE TITLE
Closure variable generates with error

### ISSUE THREAD

**Issue by evgzor** [Brightify/Cuckoo#394]
Xcode 12.5.1
Pod version 1.5.1

public protocol TestProtocol {
    var didWriteValueFor: (_ uuid: CBUUID) -> () { get set }
}

public class Test: TestProtocol {
    public var didWriteValueFor: (_ uuid: CBUUID) -> () = { fffff in }
}

MockGenerates:     

public var didWriteValueFor: (_ uuid: CBUUID) -> () {
        get {
            return DefaultValueRegistry.defaultValue(for: ((_ uuid: CBUUID) -> ()).self)
        }
        
        set { }
        
    }

Mock generates with errors

<img width="787" alt="Screenshot 2021-06-28 at 17 21 44" src="https://user-images.githubusercontent.com/5227456/123652848-52dccb00-d835-11eb-92d8-cdd9f718adc5.png">

**Comment by MatyasKriz** [comment]
Thanks for the bug report, it seems like the variable type needs to be stripped of the parameter names in this case. Does it work with just `(CBUUID) -> ()`?

**Comment by evgzor** [comment]
I used typealias at the end. No it does not work for me.

**Comment by MatyasKriz** [comment]
I see, thanks for trying it out, must be a different way then.

**Comment by sk409** [comment]
@MatyasKriz
I think the solution is to remove the argument (like ` (CBUUID) -> ()` )
Can I work on this issue to implement solution like above?

**Comment by MatyasKriz** [comment]
Hey, @sk409. Yeah, that sounds like the right solution to this. 🙂 Please go ahead.
