### ISSUE TITLE
#if Import condition is not respected

### ISSUE THREAD

**Issue by verebes1** [Brightify/Cuckoo#398]
We have a framework that has a build condition `SWIFT_ACTIVE_COMPILATION_CONDITIONS = APPEXTENSION;`
And based on that condition, we are importing the following libraries.

```Swift
#if APPEXTENSION
import CustomAppExtension
#else
import Custom
#endif
```

The problem we are facing is that the generated mocks do not have this #if statement. They import both libraries (which causes a build fail) 
like below:
```Swift
import CustomAppExtension
import Custom
```
Instead, we would require the imports to happen as in the original file:
```Swift
#if APPEXTENSION
import CustomAppExtension
#else
import Custom
#endif
```

Would it be possible to update Cuckoo to recognize that #if block?

**Comment by MatyasKriz** [comment]
I didn't notice this issue, but there's a new one that supersedes this in case of discussion: https://github.com/Brightify/Cuckoo/issues/471.
