### ISSUE TITLE
Missing input paths lead to messed up output files

### ISSUE THREAD

**Issue by bspinner** [Brightify/Cuckoo#404]
When a user provides input paths to missing files and output into multiple files is active,
the generator will mess up the output files.

## Example

Existing files: A, C
User Input: A, B, C
Generated Output files: MockA, MockB

MockB will contain output for C.
MockC will be missing.

Bug is located in `GenerateMocksCommand` as can be seen in the following excerpt.
The output loop uses `inputPathValues` as source for output paths.
But `inputPathValues` is unfiltered. Actually used files are located in `inputFiles`.

Snippet from line 72 - 77:

```swift
let inputPaths = inputPathValues.map { Path($0) }
for (inputPath, outputText) in zip(inputPaths, mergedFiles) {
    let fileName = options.filePrefix + inputPath.fileName
    let outputFile = TextFile(path: outputPath + fileName)
    try outputText |> outputFile
}
```

## Solution proposals

a. Throw an error for invalid input/missing files (breaking change)
b. Fix output paths, e.g. by using inputFiles as a source for paths.

**Comment by bspinner** [comment]
@MatyasKriz Any thoughts about the proposals?

**Comment by MatyasKriz** [comment]
Hey, @bspinner.
I think the best course of action in this case is to fix the bug itself. We can add the fail on missing files as an optional flag later if need be.
I'm actually quite surprised that Cuckoo doesn't already validate that all paths are valid before proceeding to tokenization. Do you think that would be enough to solve the issue? To filter out invalid paths from the `inputFiles` right at the beginning?

**Comment by bspinner** [comment]
Cuckoo already validates user input. Problem here is Cuckcoo's using the unvalidated/unfiltered input for output.

The filtered paths are in `inputFiles`, see https://github.com/Brightify/Cuckoo/blob/master/Generator/Source/cuckoo_generator/GenerateMocksCommand.swift#L39

`File(path: $0)` returns `nil` if the file doesn't exist.

**Comment by MatyasKriz** [comment]
Ah, I see. Then you're correct, mapping the `inputFiles` to `[Path]` is the right solution. 🙂

**Comment by MatyasKriz** [comment]
Thanks to @sk409's PR, this issue has been solved. The change will be included in the next release, but I'll close this issue now so that I don't forget. 🙂
