### ISSUE TITLE
cuckoo_generator: Bad CPU type in executable

### ISSUE THREAD

**Issue by Lawlis** [Brightify/Cuckoo#406]
Hello, after deleting derived data after a long time I wanted to run unit tests and it is failing with 
Command PhaseScriptExecution failed with a nonzero exit code

I am adding the log below

Generated Mocks File = /Users//WorkProjects///GeneratedMocks.swift
Generated Mocks File = /Users//WorkProjects///GeneratedMocksSPM.swift
Mocks Input Directory = /Users//WorkProjects///Source
Script path: /Users//Library/Developer/Xcode/DerivedData/-dbwbkrcvvqzgdebjdxqovwaxcjlh/SourcePackages/checkouts/Cuckoo
Performing clean build.
No Cuckoo Generator found.
~/Library/Developer/Xcode/DerivedData/-dbwbkrcvvqzgdebjdxqovwaxcjlh/SourcePackages/checkouts/Cuckoo ~/WorkProjects/
Downloading latest version...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3687  100  3687    0     0   6986      0 --:--:-- --:--:-- --:--:--  7090
Downloading Cuckoo Generator from URL: https://github.com/Brightify/Cuckoo/releases/download/1.5.2/cuckoo_generator
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   622  100   622    0     0   1142      0 --:--:-- --:--:-- --:--:--  1160

 13 4514k   13  626k    0     0   407k      0  0:00:11  0:00:01  0:00:10  407k
 37 4514k   37 1697k    0     0   671k      0  0:00:06  0:00:02  0:00:04 1082k
 71 4514k   71 3227k    0     0   916k      0  0:00:04  0:00:03  0:00:01 1309k
100 4514k  100 4514k    0     0   992k      0  0:00:04  0:00:04 --:--:-- 1291k
100 4514k  100 4514k    0     0   992k      0  0:00:04  0:00:04 --:--:-- 1291k
~/WorkProjects/
xargs: /Users//Library/Developer/Xcode/DerivedData/-dbwbkrcvvqzgdebjdxqovwaxcjlh/SourcePackages/checkouts/Cuckoo/cuckoo_generator: Bad CPU type in executable
Script path: /Users//Library/Developer/Xcode/DerivedData/-dbwbkrcvvqzgdebjdxqovwaxcjlh/SourcePackages/checkouts/Cuckoo
Performing clean build.
No Cuckoo Generator found.
~/Library/Developer/Xcode/DerivedData/-dbwbkrcvvqzgdebjdxqovwaxcjlh/SourcePackages/checkouts/Cuckoo ~/WorkProjects/
Downloading latest version...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3687  100  3687    0     0   8943      0 --:--:-- --:--:-- --:--:--  9126
Downloading Cuckoo Generator from URL: https://github.com/Brightify/Cuckoo/releases/download/1.5.2/cuckoo_generator
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   622  100   622    0     0   1374      0 --:--:-- --:--:-- --:--:--  1407

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 19 4514k   19  892k    0     0   586k      0  0:00:07  0:00:01  0:00:06  888k
 40 4514k   40 1812k    0     0   714k      0  0:00:06  0:00:02  0:00:04  897k
 63 4514k   63 2883k    0     0   818k      0  0:00:05  0:00:03  0:00:02  958k
 86 4514k   86 3921k    0     0   865k      0  0:00:05  0:00:04  0:00:01  977k
100 4514k  100 4514k    0     0   897k      0  0:00:05  0:00:05 --:--:-- 1000k
~/WorkProjects/
xargs: /Users//Library/Developer/Xcode/DerivedData/-dbwbkrcvvqzgdebjdxqovwaxcjlh/SourcePackages/checkouts/Cuckoo/cuckoo_generator: Bad CPU type in executable

**Comment by Lawlis** [comment]
Also, I am using an Intel-based Mac, not an M1

**Comment by Lawlis** [comment]
WORKAROUND: Downloading cuckoo generator version 1.5.1 and adding it to derived data folder where cuckoo is checked out everything works fine

**Comment by JeanAzzopardi** [comment]
I'm also getting this issue on an intel based Mac.

**Comment by MatyasKriz** [comment]
I'm sorry for the inconvenience. I've recently switched to an M1 and it seems that this caused the issue to occur. I'll re-release on an Intel Mac to counteract this.

**Comment by MatyasKriz** [comment]
Fortunately I found a way to make the executable work for both Intel and M1 Macs, I've updated the `1.5.2` release binary, could you please try it out? If it works for all of you here as well, I'll make an official `1.5.3` release.

**Comment by kamilpowalowski** [comment]
Fresh binary version works for me on Bitrise (they have intel macs).

**Comment by Lawlis** [comment]
@MatyasKriz just deleted derived data and downloaded 1.5.2 release binary, it seems to be working now.

**Comment by MatyasKriz** [comment]
@kamilpowalowski @Lawlis Thank you both so much! 🙂 After some thought, environments that build Cuckoo Generator locally don't require this change, so I'll just merge this to `master` so that newly released binaries work for both Intel and M1 Macs.

**Comment by MatyasKriz** [comment]
I'll close the issue for now, let me know if this comes up again. 🙂
