### ISSUE TITLE
Missing cuckoo_generator

### ISSUE THREAD

**Issue by puzzlemoondev** [Brightify/Cuckoo#411]
Pods/Cuckoo/run fails with `Pods/Cuckoo/cuckoo_generator: line 1: Not: command not found` because 1.6.0 release asset is missing cuckoo_generator.

**Comment by anemanja** [comment]
I encountered the same problem while trying to get things to work via SPM. Dabbled a little with the scripts and came to the source of the problem. Just need someone to fix it now.

The urls:
https://api.github.com/repos/Brightify/Cuckoo/releases/latest 
https://api.github.com/repos/Brightify/Cuckoo/releases/tags/1.6.0
don't contain the link: 

"browser_download_url": "https://github.com/Brightify/Cuckoo/releases/download/1.5.0/cuckoo_generator"

so the run script can't find it when a version is not specified or when it is specified to 1.6.0.

I understand that the new version might not have the generator updated, but as this is the way that the run script works, I think you should always include all the browser_download_url.

The workaround is to downgrade to 1.5.2 and specify it as the version for the run script:

`"${PROJECT_DIR}/run" --download 1.5.2`
