### ISSUE TITLE
 Concurrency is only available in iOS 15.0.0 or newer

### ISSUE THREAD

**Issue by bupojung** [Brightify/Cuckoo#413]
xcode 13.1
Cuckoo 1.6.0

run test with error " Concurrency is only available in iOS 15.0.0 or newer"
the cuckoo pod swift version is 5.0
how can i fix it.
![image](https://user-images.githubusercontent.com/1523163/152675782-c506ae19-0716-4629-b6e7-4dec9c26c5d5.png)

**Comment by MatyasKriz** [comment]
That's actually a known issue for Xcode 13, it has been fixed in 13.2.1 I believe. 🙂

**Comment by bupojung** [comment]
@MatyasKriz thanks for your reply.  I fix it by using cuckoo 1.5.2, because my project did not use any feature of concurrency. 
I will try to upgrade my xcode to 13.2.1 later

**Comment by MatyasKriz** [comment]
Alright, though I'll take a look at using the new version in a sample iOS 12 project, we should keep this backwards compatible, so I'll make the fix if that's not the case.

**Comment by MatyasKriz** [comment]
I've set up an iOS 12 project that runs just fine with Cuckoo 1.6.0 in Xcode 13.2.1, could you provide a specific call that is problematic?
