### ISSUE TITLE
Failed to generate mocks with property wrapper

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [Brightify/Cuckoo#428]
Hello! I'm getting a phase script error of `/Pods/Cuckoo/cuckoo_generator: terminated with signal 4; aborting`. 

I have narrowed it down and believe it's the following line that's causing an issue

`@LazyInjected(Container.service) private var service`

**Comment by MatyasKriz** [comment]
I see, thanks for the report! Do you think just ignoring the wrapper would be a sufficient fix?

**Comment by andreasziegl** [comment]
Hi @MatyasKriz,

we have the same issue. We always define protocols and the corresponding class in one file and generate the mocks via --no-class-mocking. Even in this scenario the error occurs. 
--exclude does unfortunately also not help

**Comment by kabiroberai** [comment]
fyi this appears to be a duplicate of #341. I have a fix I'll be making a PR for soon (https://github.com/kabiroberai/Cuckoo/commit/7ea36690c8ad2587004aed2e5229bbd92e4128d9) — this doesn't allow you to mock property wrappers with inferred types but at least it allows Cuckoo to parse the file without halting and catching fire.
