### ISSUE TITLE
Warning in generated code: No 'async' operations occur within 'await' expression

### ISSUE THREAD

**Issue by JavaAdam** [Brightify/Cuckoo#432]
A new warning appears concerning the Cuckoo.MockManager.crashOnProtocolSuperclassCall() for every mocked async function in my project. What seems to be correct as Cuckoo.MockManager.crashOnProtocolSuperclassCall is not an async function.

This is disturbing as I try to keep my projects warning free. 

I am missing something or is that an unexpected (or even expected) behavior?

Info:

- I have updated Cuckoo by SwiftPM and the cuckoo_generator to 1.8.1.
- Appears in Xcode 13.4.1
- The mocked protocol extends AnyObject

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/11473917/185063598-b65ae697-bb9c-4b12-b862-062020da17f6.png">

**Comment by MatyasKriz** [comment]
Hey, @JavaAdam! This has just been fixed in the newly released `1.9.0` version.

This is a change in the mock generator, so add the `--clean` flag to the `run` script. 🙂

**Comment by JavaAdam** [comment]
Hi. @MatyasKriz I have somehow missed the newest release. It works as expected now. Thank you. 🙏
