### ISSUE TITLE
Unit Test failed with XCTAssertNotNil which asserts Cuckoo_macOSTests.ExcludedTestClass is not nil

### ISSUE THREAD

**Issue by sk409** [Brightify/Cuckoo#436]
After I cloned Cuckoo's master branch and then run Unit Test(command + u), Unit Test failed with XCTAssertNotNil which asserts Cuckoo_macOSTests.ExcludeTestClass is not nil.

・Mac
macOS Monterey 12.5.1

・Xcode
13.4.1

<img width="1014" alt="スクリーンショット 2022-09-11 17 19 58" src="https://user-images.githubusercontent.com/25968819/189518390-a904a4b5-9b4b-4844-8fb4-6b79c016c31d.png">

**Comment by MatyasKriz** [comment]
Closing, as the Tuist changes have been merged to master. 🙂 I've tried running tests on all platforms (they're much more consistent now) and all of them pass.
