### ISSUE TITLE
Method cannot be declared public because its parameter uses an internal type

### ISSUE THREAD

**Issue by verebes1** [Brightify/Cuckoo#437]
Since updating to the latest version, I am getting build errors in GeneratedMocks due to type accessibility.
Property cannot be declared public because its type uses an internal type
or 
Method cannot be declared public because its parameter uses an internal type

For example:

I have the following public class
```Swift
public class client {
    internal var delegates: [ClientDelegate]
}

class [ClientDelegate] {
}
```

However, cuckoo is trying to make the delegates var public:

```Swift
public override var delegates: [ClientDelegate] {
        get {
            return cuckoo_manager.getter("delegates",
                superclassCall:
                    
                    super.delegates
                    ,
                defaultCall: __defaultImplStub!.delegates)
        }
        
        set {
            cuckoo_manager.setter("delegates",
                value: newValue,
                superclassCall:
                    
                    super.delegates = newValue
                    ,
                defaultCall: __defaultImplStub!.delegates = newValue)
        }
    }
```

We do not want to make ClientDelegate a public class (this is a framework we are building) and we need the var to be internal so its value can easily be queried by tests.

I see this has been mentioned in issue #292 and addressed in PR #293 
But the issue came back. Is there a way to solve this?

**Comment by MatyasKriz** [comment]
I've looked around the code and it seems that this issue is a bit more complex and I can't just revert the code that fixes the use-case in issue https://github.com/Brightify/Cuckoo/issues/316. That fix forces the property accessibility to the same level of the parent, but I understand your use-case as well. A workaround for now would be to make the internal type `public`.

**Comment by MatyasKriz** [comment]
No reactions and no minimal reproducible project, so I'll close this for now.
