### ISSUE TITLE
[Suggestion] Swift Package Manager plugin

### ISSUE THREAD

**Issue by jzaczek** [Brightify/Cuckoo#438]
Hello,

First of all thanks for all the good work, guys. We've been using Cuckoo as a cocoapod for a long time now and we're currently in a process of trasitioning to use SPM as our only package manager.

Is there currenty any option to run Cuckoo generator inside a SPM package? I've read the Readme, but the  instructions for SPM installation describe steps needed to use the generator inside a XCode project, not a SPM package.

The correct way to allow for generator usage inside a package would be to utilize SPM Plugins which are now supported in Xcode 14. A good example of that is [SwiftGenPlugin](https://github.com/SwiftGen/SwiftGenPlugin). I thinkt the first step towards allowing the community to build such a plugin is to expose an [artifact bundle](https://theswiftdev.com/introduction-to-spm-artifact-bundles/) through github. 

Is that currently possible for Cuckoo?

Thanks.

**Comment by MatyasKriz** [comment]
Hey there, it sounds to me like this could help with distributing the Cuckoo Generator for SPM users. I don't think there's a risk of this breaking either CocoaPods or Carthage integration, so if you create a PR, I think we can add this functionality. 🙂

Until then, each release here on GitHub contains a universal binary that you may download and execute.

**Comment by Velin92** [comment]
+ 1
