### ISSUE TITLE
Working with multiple Projects in one Workspace 

### ISSUE THREAD

**Issue by RamiroRamirez** [Brightify/Cuckoo#440]
Lets say I have three different projects in my workspace, first is DataLayer, containing only data related logic, DomainLayer, containing all the business logic and UILayer, which is responsible of UI presentation.

<img width="204" alt="Screenshot 2022-12-22 at 18 32 19" src="https://user-images.githubusercontent.com/9657465/209192880-d6c2b829-3d1e-413d-81e3-e0a3b215152f.png">

To make this architecture works, some rules are: 

DataLayer can (or should) import DomainLayer
DomainLayer should not have any dependencies
UILayer should not know Interactor(DomainLayer). It should be behind of UseCase protocol (included in DomainLayer).

My question is: I want to include cuckoo to test this project, but as I need to add some imports in generated files including mocks (UILayer implements protocols that are defined in Domain Layer and also DataLayer needs to include DomainLayer), is there a way to include this imports manually? Is it possible to use Cuckoo with this kind of setup?

Thanks in advance!

**Comment by MatyasKriz** [comment]
Hey @RamiroRamirez, the parameter `--testable` passed into the generator is usually a single target, but you may pass multiple, [as per the README](https://github.com/Brightify/Cuckoo#--testable-stringstring). 🙂 Let me know if that helped.
