### ISSUE TITLE
Permission denied: Can't add comments to the list of files

### ISSUE THREAD

**Issue by ppamorim** [Brightify/Cuckoo#461]
Similar to #385.

I have hundreds of files and I would like to organise them better like this:

```
# Manager

"${INPUT_DIR}/Manager/FooManager.swift" \

# ViewModel

"${INPUT_DIR}/ViewModel/HomeViewModel" \
"${INPUT_DIR}/ViewModel/AuthViewModel"
```

It's returning `Permission denied`. Cuckoo could ignore those comments.

**Comment by MatyasKriz** [comment]
Hey @ppamorim, does something like this work?

```bash
#Manager \
"${INPUT_DIR}/Manager/FooManager.swift" \
# ViewModel \
"${INPUT_DIR}/ViewModel/HomeViewModel" \
"${INPUT_DIR}/ViewModel/AuthViewModel"
```

If not, I'm afraid there's not much we can do. This is simply bash, if you don't append the backslash, the next line is executed as a command.

**Comment by ppamorim** [comment]
@MatyasKriz It doesn't work, the file doesn't get processed and returns `Permission denied` again.

**Comment by MatyasKriz** [comment]
Alright, then I've come up with a simple way to organize your files in a bash script:

```bash
input_files=()

# Managers
input_files+=(
  "blekeke a rekeke"
  "frekeke"
)

# View models
input_files+=(
  "something"
  "anything"
  "pelekese"
)

run ${input_files[@]}
```

**Comment by MatyasKriz** [comment]
@ppamorim does the script above work? If so, I think we can close this, if there were some changes necessary, I'd appreciate if you shared them here. 🙂
