### ISSUE TITLE
Unable to build with SPM install (ld: symbol(s) not found for architecture arm64)

### ISSUE THREAD

**Issue by kelvinharron** [Brightify/Cuckoo#467]
Hi folks. We've used Cuckoo to great success in a previous project (with Cocoapods) and while spiking out a skeleton app for a new project, I've encountered a blocker in trying to set Cuckoo up with SPM.

## The problem

After following the instructions for SPM -> Clean & Build, I get the following error lines.

>ld: warning: Could not find or use auto-linked library 'XCTestSwiftSupport'
ld: warning: Could not find or use auto-linked framework 'XCTest'
Undefined symbols for architecture arm64:
  "_$s6XCTest7XCTFail_4file4lineySS_s12StaticStringVSutF", referenced from:
      _$s6Cuckoo11MockManagerC4failyySS7message_s12StaticStringV4file_Su4linet14sourceLocationt_tcvpZfiySSAE_AgH_SuAItAJt_tcfU_ in Cuckoo.o
  "__swift_FORCE_LOAD_$_XCTestSwiftSupport", referenced from:
      __swift_FORCE_LOAD_$_XCTestSwiftSupport_$_Cuckoo in Cuckoo.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Where the three failures are down to this
<img width="972" alt="Screenshot 2023-05-31 at 10 27 38" src="https://github.com/Brightify/Cuckoo/assets/16445381/dc83c92e-93ff-4f1e-a762-422660737555">

## Steps to reproduce

To rule out our project being the cause, I was able to reproduce it entirely with a brand-new iOS project.

* Xcode 14.3 on an M1 Macbook Pro. macOS Ventura 13.3.1
* Create a new iOS project with add Tests checked.
* Add Cuckoo via SPM (with version rules 1.9.1 - Next Major).
* Add the Run script above Compile Sources on the Test target.
* Executed the run script on the project root.
* Replace `"${PODS_ROOT}/Cuckoo/run"` with `"${PROJECT_DIR}/run" --download`
* Clean & Build.

<details>
<summary>Run Script</summary>

```
if [ $ACTION == "indexbuild" ]; then
  echo "Not running Cuckoo generator during indexing."
  exit 0
fi

# Skip for preview builds
if [ "${ENABLE_PREVIEWS}" = "YES" ]; then
  echo "Not running Cuckoo generator during preview builds."
  exit 0
fi

# Define output file. Change "${PROJECT_DIR}/${PROJECT_NAME}Tests" to your test's root source folder, if it's not the default name.
OUTPUT_FILE="${PROJECT_DIR}/${PROJECT_NAME}Tests/GeneratedMocks.swift"
echo "Generated Mocks File = ${OUTPUT_FILE}"

# Define input directory. Change "${PROJECT_DIR}/${PROJECT_NAME}" to your project's root source folder, if it's not the default name.
INPUT_DIR="${PROJECT_DIR}/${PROJECT_NAME}"
echo "Mocks Input Directory = ${INPUT_DIR}"

# Generate mock files, include as many input files as you'd like to create mocks for.
"${PROJECT_DIR}/run" --download generate --testable "${PROJECT_NAME}" \
--output "${OUTPUT_FILE}" \
"${INPUT_DIR}/ViewModel.swift"
# ... and so forth, the last line should never end with a backslash

# After running once, locate `GeneratedMocks.swift` and drag it into your Xcode test target group.
```

</details>

I've added the project below (122KB compressed).
[CuckooSampleProject.zip](https://github.com/Brightify/Cuckoo/files/11611178/CuckooSampleProject.zip)

Please let me know what I can do to get it working. Thanks!

**Comment by kelvinharron** [comment]
SPM noob confirmed! 😆 

The problem was when adding Cuckoo via SPM, I was adding it to the app project and not the tests explicitly. Resolved now!
<img width="660" alt="Screenshot 2023-05-31 at 10 58 36" src="https://github.com/Brightify/Cuckoo/assets/16445381/e6fd7db0-6a16-4922-b08c-36a32c3c6cf9">

I'm happy to create a PR to update the README to be explicit about this if that helps!

**Comment by MatyasKriz** [comment]
Hey @kelvinharron, a PR that would help make this clear for others in the README would definitely be appreciated if you're willing. 🙂 And good job on finding that out yourself!

**Comment by 0x7067** [comment]
I'm having the same issue, even if I'm adding it to the test target

**Comment by 0x7067** [comment]
Found out what was the issue: I had the `GeneratedMocks.swift` file added to the app project's target and not the test target

**Comment by kelvinharron** [comment]
Nice one, @0x7067 ! I think that would make a nice explicit addition to the project README! 😄

**Comment by 0x7067** [comment]
I agree! Will open a PR later with an edited README
