### ISSUE TITLE
Issue with variable name as `extension`

### ISSUE THREAD

**Issue by levantAJ** [Brightify/Cuckoo#481]
Hi team I ran into an issue in my class there is a variable named `extension`, when generating the mocks I get this error message 

```
Getter/setter can only be defined for a single variable
Keyword 'extension' cannot be used as an identifier here
If this name is unavoidable, use backticks to escape it
```

The class looks like:

```swift
class PurchasePathInterfaceProxy: NSObject, PurchasePathInterface {
    var `extension`: PurchasePathExtension?

    var isBrowserEnabled: Bool = false

    func fetch(request: PurchasePathRequest, completion: @escaping (PurchasePath?, Error?) -> Void) {
    }
}
```

<img width="990" alt="Screenshot 2023-12-19 at 16 31 35" src="https://github.com/Brightify/Cuckoo/assets/6329656/e03071e5-1d87-4fd4-beb4-0b92af0b60bb">

**Comment by MatyasKriz** [comment]
It seems like the support for escaping keywords wasn't extended to property names. I assume that it was merely forgotten.

I'll fix this for the upcoming 2.0 release. Thanks for noticing this! 🙂
