### ISSUE TITLE
2.0 issues

### ISSUE THREAD

**Issue by MatyasKriz** [Brightify/Cuckoo#489]
I'm realistic and since virtually nobody joined the testing phase, I'm sure there's bugs in the 2.0 release as there are a LOT of changes and the tests surely don't cover all the possible use-cases.

If you've encountered an issue, please open it like you would and then link it here so that I know which issues to prioritize.

Alternatively, if you wish to stay on 1.x.x version, pass `--download 1.10.4` to the `run` script.

**Comment by aaronbarsky** [comment]
2.0.1 issue: https://github.com/Brightify/Cuckoo/issues/491

**Comment by JavaAdam** [comment]
2.0.3 issue: https://github.com/Brightify/Cuckoo/issues/494

**Comment by MatyasKriz** [comment]
I'm closing this since it's starting to look better and the issues we're getting are unique.
