### ISSUE TITLE
Unsupported attribute 'objc'

### ISSUE THREAD

**Issue by luigigre** [Brightify/Cuckoo#490]
Hi, upgrading to 2.0 made the script give out errors on classes that were mocked correctly before when using @objc and @objcMembers

Example:
`@objc protocol SomeProtocol { }`
`@objcMembers class SomeClass: NSObject, SomeProtocol {}`

Running this script will throw
`Unsupported attribute 'objc'`
`Unsupported attribute 'objcMembers'`

And these classes will be skipped from the mocking phase.
The same classes were correctly mocked on 1.10.3.

Did something change that needs to be addressed on my side? Any help or clarification is appreciated

**Comment by MatyasKriz** [comment]
Hey, @luigigre. Thanks for pointing this out! It seems like this was undocumented behavior (and not part of the unit tests the project has) and I must have missed it when porting all the functionalities to SwiftSyntax.

I'll get right to it, it shouldn't be hard to add back.

**Comment by luigigre** [comment]
Yes you're right, the message "unsupported attribute" was throwing me off but apparently that's not actually my problem, since the class appears to be mocked but the same tests are not compiling, it's throwing a lot of "unterminated string literal" in the GeneratedMocks file, I'm investigating it so if necessary I will open a separate issue with more details

**Comment by MatyasKriz** [comment]
If you could share an example of the code that generates uncompilable mocks, that would be most appreciated as I'd add it to the tests and fix it.
