### ISSUE TITLE
Generator v2: Generic Restrictions on Method missing

### ISSUE THREAD

**Issue by alexdm-e2n** [Brightify/Cuckoo#497]
A class with the following func is mocked.

```
class GraphQLClient {
  func fetch<Query: ApolloAPI.GraphQLQuery>(query: Query) async -> Result<Query.Data.Model, Error> { ... }
}
```

Cuckoo v2:
```
class MockGraphQLClient: GraphQLClient, Cuckoo.ClassMock {
  override func fetch<Query> (query p0: Query) async -> Result<Query.Data.Model, Error> { ...
  }
}
```

Issue: Mock cannot compile because of the missing protocol restriction `<Query: ApolloAPI.GraphQLQuery>`.

Cuckoo v1:
```
class MockGraphQLClient: GraphQLClient, Cuckoo.ClassMock {
  override func fetch<Query: ApolloAPI.GraphQLQuery>(query: Query) async -> Result<Query.Data.Model, Error> { ...
  }
}
```

I expected the code like v1. Am I missing a configuration option here or is this an issue?

**Comment by MatyasKriz** [comment]
This is definitely a bug, thank you for bringing it to light. 🙂

**Comment by MatyasKriz** [comment]
Should be fixed in version 2.0.5, please try it out and let me know if you find any other issues, thanks again!

**Comment by alexdm-e2n** [comment]
@MatyasKriz Thank you for your fast response. Unfortunately the issue exists still in 2.0.5.

```
override func fetch<Query> (query p0: Query) async -> Result<Query.Data.Model, Error> where Query.Data: ModelConvertible {
...
}
```

The mocked method is
```
func fetch<Query: ApolloAPI.GraphQLQuery>(query: Query) async -> Result<Query.Data.Model, Error> where Query.Data: ModelConvertible {
...
}
```

**Comment by alexdm-e2n** [comment]
Thank you for your fast response. After clearing the full project it worked. Thank you! 👍
