### ISSUE TITLE
PropertyObservers affecting mocked property generation.

### ISSUE THREAD

**Issue by Marquis103** [Brightify/Cuckoo#501]
This is something new in Cuckoo 2 that was not in the original version. If I have a property say:

```
var number: Int = 0 {
  didSet {
    print("\(number)")
  }
}
```

The mock for this property will be:

```
    override var number: Int {
        get {
            return cuckoo_manager.getter(
                "number",
                superclassCall: super.number,
                defaultCall: __defaultImplStub!.number
            )
        }
    }
```

Naturally we will get an error here because we are overriding a mutable property with a read-only implementation. When I switch to the latest version of the original cuckoo it doesn't do that. Even more, if I remove the didSet:

```
var number: Int = 0
```

It will override ride the property with its expected getter and setter.

Any thoughts or assistance anyone can provide on this?

**Comment by MatyasKriz** [comment]
Hey, @Marquis103, thanks for the report, this is simply an oversight when converting from SourceKitten to SwiftSyntax.

During this we can see how incomplete our tests were. 😄 I'll take a look at it.

**Comment by Marquis103** [comment]
Thanks @MatyasKriz for the speedy response

**Comment by MatyasKriz** [comment]
I've fixed this one, thanks for reporting it. 🙂

However, I'm having some problems releasing a new version because of Xcode update, I'll take a look at it as soon as I can.

**Comment by MatyasKriz** [comment]
Fixed and released. Enjoy!
