### ISSUE TITLE
EXC_BAD_ACCESS on Xcode 16 Beta

### ISSUE THREAD

**Issue by alxdenis** [Brightify/Cuckoo#506]
Hello all,

I installed Xcode 16 beta 4 to try my app on iOS 18.
I face some difficulties while running my XCTests.
Now, some method calls of Cuckoo mocks produce this crash:

`Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`

Do you encounter this issue on Xcode 16 ?

Thank you all

**Comment by aiKrice** [comment]
Which version of cuckoo are you using ?
Which package manager are you using ?
