### ISSUE TITLE
Allow swift-syntax up to v510.0.3

### ISSUE THREAD

**Issue by alexdm-e2n** [Brightify/Cuckoo#509]
Current dependency ist exact swift-syntax v509.0.0. This forces other dependencies e.g. swiftlint to much lower versions.

Do you require the exact version or is a minor-version dependency possible so you can loosen the requirements a bit?

**Comment by MatyasKriz** [comment]
Hey, as long as the Cuckoo project compiles, I don't think that exact SwiftSyntax version is required. 🙂 Could you please open a PR if it works so other users can benefit as well?

**Comment by alexdm-e2n** [comment]
Unfortunately the loosening is not enough. To support swift 6 it is also necessary to switch to major revision 600 which has just bee released yet.

**Comment by BjoernLindner** [comment]
please reopen, swift-syntax version 600 is still important for newer projects

**Comment by MatyasKriz** [comment]
> please reopen, swift-syntax version 600 is still important for newer projects

I understand, but simply changing SwiftSyntax to 600 doesn't change the fact that stuff like typed throws and what not needs to be implemented to be supported, these features don't come free with the parser. I'll open a new issue which will compile every syntax change that needs to be supported from Swift 6.

**Comment by tejassharma96** [comment]
I just opened https://github.com/Brightify/Cuckoo/issues/547, which is somewhat related - please see the article linked there regarding being a good citizen in the land of swift syntax
