### ISSUE TITLE
Cuckoo + SPM = Not working (Cannot find 'Glibc' in scope for XcodeProj dependency)

### ISSUE THREAD

**Issue by DmitryKalenkov** [Brightify/Cuckoo#514]
Hello! I faced with an issue, my steps:
Add Package Dependency > https://github.com/Brightify/Cuckoo.git
Add 2 Packages (Cuckoo, CuckooGenerator) to test Target.
GOTO > Build Phases > Run Build Tool Plug-ins > add CuckooPluginSingleFile(Cuckoo)

Build teset target (Cmd+shift+U) > Build failed
Package from CuckooGenerator, XcodeProj mark an error: "Cannot find 'Glibc' in scope".
![Screen2](https://github.com/user-attachments/assets/bbc40aa1-951d-44b7-8fa6-622f5a515177)
![Screen1](https://github.com/user-attachments/assets/0821915b-e66b-4df3-adcc-ae83c0537df7)

![Screenshot_24-10-04](https://github.com/user-attachments/assets/c609feca-9e8f-4a48-aed0-a2dae94d1088)

What am i doing wrong? Thanks!

**Comment by MatyasKriz** [comment]
Hey, simply remove the `CuckooGenerator` dependency and you're set. We'll need to find a way to not offer that target in Xcode, because this happens pretty often.
