### ISSUE TITLE
Swift Testing verify is not working

### ISSUE THREAD

**Issue by dr-star** [Brightify/Cuckoo#517]
The verify method doesn't work properly when using with Swift Testing library.

Given 
```
verify(fidelityCardService, times(1)).getFidelityCardDetails(storeId: equal(to: storeId), fidelityCardId: equal(to: fidelityCardId))
```

is ignoring the parameter times(X) when class is not a subclass of XCTestCase.  [Migrating a test from XCTest
](https://developer.apple.com/documentation/testing/migratingfromxctest#Convert-test-classes)

In case the class is a subclass the test fails **as expected**

**Comment by aiKrice** [comment]
Encountered same issue here.

**Comment by clementcasa** [comment]
I have the same issue on my tests, I had to roll back to XCTest.
