### ISSUE TITLE
Installing > 2.0 version

### ISSUE THREAD

**Issue by Dancargon** [Brightify/Cuckoo#525]
Hi!
I've installed Cocoapod version 2.0.9. 
It generates the GeneratedMocks file but It fails to compile with a message:

`Global function 'when' requires that 'MockGraphQlClientProtocol.Stubbing' (aka 'MockGraphQlClientProtocol.__StubbingProxy_GraphQlClientProtocol') conform to 'BaseStubFunctionTrait'`

on all instances of `when` similar to this:
```
graphQlClientMock = MockGraphQlClientProtocol()
stub(graphQlClientMock) { stub in
	when(stub).setup(withSession: any(), serverUrlString: any()).thenDoNothing()
}
```

`MockGraphQlClientProtocol` seems to be generated successfully in the GeneratedMocks file.

Any feedback will be much appreciated.

Thanks!

**Comment by MatyasKriz** [comment]
Yes, Cuckoo 1 allowed an unintentional syntax of `when(stub).method(...).thenX`, but Cuckoo 2 enforces the intended syntax of `when(stub.method(...)).thenX`.

Basically the method call needs to be inside the `when` call, not after it.

**Comment by Dancargon** [comment]
Thanks, it's fixed.
Much appreciated!
