### ISSUE TITLE
[Cuckoo 2.0.10] version: No such file or directory

### ISSUE THREAD

**Issue by wei-addepar** [Brightify/Cuckoo#526]
Hi,
I have been using Cuckoo 1.x for many months now and I'm very thankful for this great library.
However, I couldn't get Cuckoo 2.0.10 to work.

Migrated the content originally in the build phase script itself to the `Cuckoofile.toml` file
```
[modules.MyProject]
output = "MyProjectTests/Mocks/GeneratedMocks.swift"
testableImports = ["MyProject", "Framework1", "Framework2"]
sources = [
    "MyProject/Folder1/File1.swift",   <- file contains protocol to mock, not test file
    "MyProject/Folder1/File2.swift",   <- file contains protocol to mock, not test file
    "MyProject/Folder2/File1.swift"   <- file contains protocol to mock, not test file
]

[modules.MyProject.options]
keepDocumentation = false
protocolsOnly = true
```
However, when trying to build the test target, I get the following error:

/Users/myusername/MyProjectRoot/Pods/Cuckoo/run: line 89: version: No such file or directory

Have I missed any other configuration? Appreciate your help.

**Comment by wei-addepar** [comment]
Well, interestingly, the mocks were actually still generated despite of the error message.

**Comment by MatyasKriz** [comment]
Hi! It's probably not communicated well enough, but you need to replace your `run` script as well, it's been overhauled for Cuckoo 2 for syncing version of generator to runtime.
