### ISSUE TITLE
Cuckoo support for objective c

### ISSUE THREAD

**Issue by repl-ullas-ml** [Brightify/Cuckoo#53]
I want to avoid writing my own mocks for objective c classes. FYI my project contains both objective c and swift implementations.

Does cuckoo support objective c class mocks?

**Comment by TadeasKriz** [comment]
Hi, it does not support ObjC as of now, but we would like to add support for dynamic mocks that will not be precompiled, but created as a proxy of an ObjC class.

**Comment by repl-ullas-ml** [comment]
@TadeasKriz Any ETA on when would you start supporting this?

**Comment by TadeasKriz** [comment]
It's on our task list right after Swift 3.0 support. Unfortunately I cannot give you any ETA as it all depends on how much free time we'll get on our hands and how difficult will the implementation be.

**Comment by repl-ullas-ml** [comment]
@TadeasKriz Thats great news ! Thanks

**Comment by bruceflowers** [comment]
I would also like this functionality if it's still not yet supported - we have many occasions to want to mock things from a third party libraries that are still legacy Obj-C.

**Comment by MatyasKriz** [comment]
Hey there, along with @TadeasKriz we added an experimental ObjC mocking functionality that utilizes OCMock using a neat API along with all the safety that Swift can offer.

This should allow for mocking all objects from ObjC, along with the system libraries. Feel free to try the `experimental/objectiveC` branch and post any issues or proposals to PR #290. Thanks in advance!
