### ISSUE TITLE
"Illegal instruction: 4" error

### ISSUE THREAD

**Issue by che1404** [Brightify/Cuckoo#76]
Hi!
thanks for this awesome framework.
Today (without no action that I can remember) I have started experiencing this error in the cuckoo generator script: "Illegal instruction: 4"
The complete error is:

*MyProject*/Pods/Cuckoo/run: line 18: 72872 Illegal instruction: 4  $FILE_PATH/Contents/MacOS/cuckoo_generator "$@" ${INPUT_FILES}

(I'm using Xcode 8.1 and cuckoo version 0.8.0)
Any ideas?
Thanks,
Robert.

**Comment by TadeasKriz** [comment]
Hi,
when did you update to Xcode 8.2? I didn't test Cuckoo with 8.2 as it's still in beta. I think that might be the problem.

**Comment by che1404** [comment]
Hey, I meant Xcode 8.1, sorry.

**Comment by TadeasKriz** [comment]
Could you try runnin the `run` manually and send me a log? Thanks.

**Comment by che1404** [comment]
Hi,
./run generate --testable **MyProject** /Users/ro/code/**MyProject**/**MyProject**/Login/Protocols/LoginProtocols.swift --output GeneratedMocks.swift

This doesn't give any errors. Strange. Maybe the problem is in the post-build script itself?
It only happens on one of my projects.

**Comment by lvdstam** [comment]
Hi,
First: I started using this framework recently and would like to thank all that contributed for making it.

Second: I seem to have stumbled on a situation where this problem also occurs (maybe it is the same cause). It seems that it occurs when you put a class containing a var that is initialized by calling a constructor. Something like:

class SomeClass {
    var someVar = Int(5)
}
 When I run the above through the generator it reports the problem in the title.

When I move the initialization to the init() function, the generator complains, but continues to create the output file (which seems ok).

Hope this helps and keep up the good work.

**Comment by che1404** [comment]
Hi,
I cannot be 100% sure, but I think that the problem went away when I ran xcode-select pointing to the latests Xcode stable version (I was playing with the beta those days). 
I hope this helps.

**Comment by Ryce** [comment]
having the same issue with this when trying to execute from CLI

```
./run generate --testable MyProject ~/github/myproject-ios/MyProject/Task.swift --output ~/GeneratedMocks.swift
Unknown kind: source.lang.swift.decl.enumUnknown kind: source.lang.swift.expr.call./run: line 18: 63503 Illegal instruction: 4  $FILE_PATH/Contents/MacOS/cuckoo_generator "$@" ${INPUT_FILES}
```

xcode version 8.1
cuckoo 0.8.0

Any ideas?

**Comment by TadeasKriz** [comment]
Hi, do you have Xcode 8.2 installed as well? I'm trying to reproduce it, but so far I wasn't able to. Do you have any reproducer?

**Comment by Ryce** [comment]
@TadeasKriz 

nope, I am still on Xcode 8.1, I will try 8.2

**Comment by TadeasKriz** [comment]
@Ryce I'm too on 8.1, didn't try with 8.2 yet.

**Comment by lvdstam** [comment]
I have Xcode 8.1 and do not have 8.2 installed. I'm using the Pods distributed version which in pods is reported 0.8.0 but on the commandline says 0.6.0

**Comment by TadeasKriz** [comment]
@lvdstam Please show us your Podfile and the run script (or how you run it on cmdline). Thanks.

**Comment by TadeasKriz** [comment]
@lvdstam @Ryce @che1404 I just released v `0.8.1` with changes to the run script. Please give it a go and let me know. Thanks!

**Comment by lvdstam** [comment]
I have updated to the 0.8.1 version. Here the commandline correctly reports 0.8.1

**Comment by TadeasKriz** [comment]
@lvdstam And does it work correctly with your code now?

**Comment by lvdstam** [comment]
@TadeasKriz no it does not. I made a pull request showing where for me the problem of the crash is coming from...

**Comment by MatyasKriz** [comment]
I'm closing this issue as there are no open pull requests regarding this indicating that it's probably fixed but someone forgot to close the issue. By the way, thanks for the PR!
