### ISSUE TITLE
typealias in protocol definitions are not supported

### ISSUE THREAD

**Issue by lvdstam** [Brightify/Cuckoo#90]
When you have a protocol like
protocol SomeProtocol {
    typealias SomeTypeAlias = (Int) -> Int
    var someTypeAliasProperty: SomeTypeAlias
}

and feed this into the generator, the generated code fails to compile because the typealias is lost.
I consider this to be a swift problem, but still would like to solve it in part in the generator by injecting the typealias in the generated classes.

I have investigated the problem a bit, my conclusion for now is that it can not be done since sourcekitten does not return the typealias information when it parses/tokenizes a sourcefile.

Please look into this.

**Comment by lvdstam** [comment]
Actually, it may just work if in the protocol definition the fully qualified name is used when referencing the type alias:
protocol SomeProtocol {
typealias SomeTypeAlias = (Int) -> Int
var someTypeAliasProperty: SomeProtocol.SomeTypeAlias
}

**Comment by MatyasKriz** [comment]
Typealias support added to master and will be included in the next release, thank you for your patience. 🙂
