### ISSUE TITLE
protocol with init definition can not be mocked

### ISSUE THREAD

**Issue by lvdstam** [Brightify/Cuckoo#92]
The following is generated without the initializer function and therefor does not conform to the protocol.

protocol SomeProtocol {
    init(value: Int)
}

I think it would be okay to just generate the init function for a protocol mock and have it discard the arguments and/or call the no arguments init.

Please share your thoughts, I'll create the code and pull request for it.

**Comment by mrgerych** [comment]
@TadeasKriz fixed
