### ISSUE TITLE
Protocol with an associatedtype generates a mock that does not compile

### ISSUE THREAD

**Issue by lvdstam** [Brightify/Cuckoo#94]
The following fails to generate a proper mock:

protocol SomeProtocol {
    associatedtype SomeAssociatedType
    func someFunc(value: SomeAssociatedType)
}

**Comment by mattdeckard** [comment]
I'm running into the same issue. Could Cuckoo at the very least not attempt to generate mocks for these protocols, rather than generating broken code?

**Comment by samskiter** [comment]
Also running into this issue. Been using a slightly adapted version of https://github.com/AliSoftware/SourceryTemplates to type erase our protocols. Maybe cuckoo could assume the existence of some kind of Type erased type (AnyMyProtocol) if it sees associated types - seeing as it doesn't compile anyway, that would at least allow people to provide that implementation through other means.

**Comment by MatyasKriz** [comment]
Merged!
