### ISSUE TITLE
GeneratedMocks.swift does not compile

### ISSUE THREAD

**Issue by tamasoszko** [Brightify/Cuckoo#95]
I have this class to be mocked:
class SomeClass {
    func someIntMethod() -> Int {
        return 1
    }    
    func someStringMethod() -> String {
        return "a"
    }
}

the generated mock file does not compile, it seems couple of characters are missing after the method parameter declarations: " -> Int" becomes " nt",  "-> String" becomes "tring"

class MockSomeClass: SomeClass, Cuckoo.Mock {
...
    override func someIntMethod() nt {
        return manager.call("someIntMethod() nt", parameters: (), original: observed.map { o in return { () nt in o.someIntMethod() } })
    }
    
    override func someStringMethod() tring {
        return manager.call("someStringMethod() tring", parameters: (), original: observed.map { o in return { () tring in o.someStringMethod() } })
    }

Any idea ?
Thanks !

XCode Version 8.2.1 (8C1002)
PODS:
  - Cuckoo (0.8.2)

**Comment by sswierczek** [comment]
@tamasoszko I had the same issue but in my case it was only 1 character missing "-" in +"->". I had invalid generated code like this:

```
public override func getFullVideoUrl() > String {
        return DefaultValueRegistry.defaultValue(for: (Void).self)
}
```

 **It seems that in my case it was a fault of single "Ś" character in file header comment. After I removed it mocks generation works.**

1. Remove non-English characters from comments
2. Remove content of GeneratedMocks.swift file content
3. Product -> Build For -> Testing
4. Enjoy

Thanks to @awachowicz for help me solving this.

**Comment by TadeasKriz** [comment]
@sswierczek Hey, thanks for the info! There is probably a problem in how we access characters in the generator. We'll look into it.
